

CREATE TABLE STOENTRIES.TBL_SALES_PROFORMA_HDR(
	SNO INT IDENTITY(1,1)  ,
	SALES_PROFORMA_REF_NO VARCHAR(50) CONSTRAINT PK_SALES_PROFORMA_REF_NO PRIMARY KEY ,
	SALES_PROFORMA_DATE DATETIME ,
	COMPANY_ID INT CONSTRAINT FK_SALES_PROFORMA_COMPANY_ID FOREIGN KEY REFERENCES STOMASTER.TBL_COMPANY_MASTER (COMPANY_ID),-- DROP DOWN
	STORE_ID INT CONSTRAINT FK_SALES_PROFORMA_STORE_ID FOREIGN KEY REFERENCES STOMASTER.TBL_STORE_MASTER (STORE_ID),-- DROP DOWN
	CUSTOMER_ID INT CONSTRAINT FK_SALES_PROFORMA_CUSTOMER_ID FOREIGN KEY REFERENCES STOMASTER.TBL_CUSTOMER_MASTER (CUSTOMER_ID) ,-- DROP DOWN
	BILLING_LOCATION_ID INT CONSTRAINT FK_SALES_PROFORMA_BILLING_LOCATION_ID FOREIGN KEY REFERENCES STOMASTER.TBL_BILLING_LOCATION_MASTER(BILLING_LOCATION_ID),-- DROP DOWNN PIACK 
	SALES_PERSON_EMP_ID INT CONSTRAINT FK_SALES_PERSON_SAO FOREIGN KEY REFERENCES STOMASTER.TBL_SALES_PERSON_MASTER(SALES_PERSON_ID), -- DROP DOWN
	CURRENCY_ID INT CONSTRAINT FK_CURRENCY_ID_DEL FOREIGN KEY REFERENCES STOMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID),-- DROPDOWN
	EXCHANGE_RATE DECIMAL(15,2),-- PICK FROM MASTER BY USING CURRENCY LAST ENTRY
	[TOTAL_PRODUCT_AMOUNT] DECIMAL(15,4),-- FORMAULE =  [TOTAL_QTY] X [SALES_RATE_PER_QTY]
	[VAT_AMOUNT] DECIMAL(15,4), -- FORMAULE [TOTAL_PRODUCT_AMOUNT] X [VAT_PERCENTAGE]/100
	[FINAL_SALES_AMOUNT] DECIMAL(15,4),-- FORMAULE =  [TOTAL_PRODUCT_AMOUNT] + [VAT_AMOUNT]
	[TOTAL_PRODUCT_AMOUNT_LC] DECIMAL(15,4),-- FORMULAE = [TOTAL_PRODUCT_AMOUNT]*EXCHANGE RATE  -- JUST BACKEND
	[FINAL_SALES_AMOUNT_LC] DECIMAL(15,4), -- [FINAL_PRODUCT_AMOUNT] X EXCHANGE RATE -- JUST BACK END
	REMARKS VARCHAR(2000) ,
	TEST_DESC VARCHAR(50) , -- DEFAULT "NA" -- BACKEND
	STATUS_ENTRY VARCHAR(20) ,
	CREATED_BY VARCHAR(50) ,
	CREATED_DATE DATETIME ,
	CREATED_MAC_ADDRESS VARCHAR(50) ,
	MODIFIED_BY VARCHAR(50) ,
	MODIFIED_DATE DATETIME ,
	MODIFIED_MAC_ADDRESS VARCHAR(50) ,
	SUBMITTED_BY VARCHAR(50),
	SUBMITTED_DATE DATETIME
	)
	GO
	
	
CREATE TABLE STOENTRIES.TBL_SALES_PROFORMA_DTL(
	SNO INT IDENTITY(1,1)  CONSTRAINT PK_SNO_SO_DTL PRIMARY KEY ,
	SALES_PROFORMA_REF_NO VARCHAR(50) CONSTRAINT FK_SALES_PROFORMA_REF_NO FOREIGN KEY REFERENCES STOENTRIES.TBL_SALES_PROFORMA_HDR (SALES_PROFORMA_REF_NO) ,--FK
	MAIN_CATEGORY_ID INT CONSTRAINT FK_SALES_PROFORMA_MAIN_ID FOREIGN KEY REFERENCES STOMASTER.TBL_PRODUCT_MAIN_CATEGORY_MASTER (MAIN_CATEGORY_ID) ,-- DROP DOWN
	SUB_CATEGORY_ID INT CONSTRAINT FK_SALES_PROFORMA_SUB_ID FOREIGN KEY REFERENCES STOMASTER.TBL_PRODUCT_SUB_CATEGORY_MASTER (SUB_CATEGORY_ID) ,-- DROP DOWN
	PRODUCT_ID INT  CONSTRAINT FK_SALES_PROFORMA_PRODUCT_ID FOREIGN KEY REFERENCES STOMASTER.TBL_PRODUCT_MASTER (PRODUCT_ID),-- DROP DOWN WITH NAME SEARCH
	STORE_STOCK_PCS DECIMAL(15, 4) ,--- STORE AND PRODUCT WISE STOCK QTY
	PO_REF_NO VARCHAR(50) CONSTRAINT FK_PROFORMA_REF_NO_SO_DTL FOREIGN KEY REFERENCES STOENTRIES.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),-- DROP DOWN LOAD BASED ON SELECTED PRODUCT ID
	PO_DTL_SNO INT CONSTRAINT FK_PO_DTL_SNO_SO_DT_PROFORMA FOREIGN KEY REFERENCES STOENTRIES.TBL_PURCHASE_ORDER_DTL(SNO),-- AUTO SELECT PO NO AND SELECTE PRODUCT ID 
	PO_DTL_STOCK_QTY DECIMAL(15,4), -- STORE,PO DTL SNO AND PRODUCT WISE QTY
	[PURCHASE_RATE_PER_QTY] DECIMAL(15,6),-- LABEL DATA PICK FROM PO RATE
	PO_EXPENSE_AMOUNT DECIMAL(15,4),-- SUM OF TOTAL PO EXPENSES AGAINST SELECTED PO AND PO SNO
	[SALES_RATE_PER_QTY] DECIMAL(15,6),-- TEXT
	[QTY_PER_PACKING] DECIMAL(15,2),-- LABEL PICK FROM [STOMASTER].[TBL_PRODUCT_MASTER]-- SELECTED PRODUCT
	[TOTAL_QTY] DECIMAL(15,4),-- TEXT --
	[UOM] VARCHAR(50),-- LABEL PICK FROM [STOMASTER].[TBL_PRODUCT_MASTER]-- SELECTED PRODUCT
	[TOTAL_PACKING] DECIMAL(15,4),--LABEL FORMULAE =  [TOTAL_QTY]*[QTY_PER_PACKING]
	[ALTERNATE_UOM] VARCHAR(500),-- -- LABEL PICK FROM [STOMASTER].[TBL_PRODUCT_MASTER]-- SELECTED PRODUCT
	[TOTAL_PRODUCT_AMOUNT] DECIMAL(15,4),-- FORMAULE =  [TOTAL_QTY] X [SALES_RATE_PER_QTY]
	[VAT_PERCENTAGE] DECIMAL(15,2),-- FORMAULE WRITE USER DEFINED FUNCTION GET VAT %
	[VAT_AMOUNT] DECIMAL(15,4), -- FORMAULE [TOTAL_PRODUCT_AMOUNT] X [VAT_PERCENTAGE]/100
	[FINAL_SALES_AMOUNT] DECIMAL(15,4),-- FORMAULE =  [TOTAL_PRODUCT_AMOUNT] + [VAT_AMOUNT]
	[TOTAL_PRODUCT_AMOUNT_LC] DECIMAL(15,4),-- FORMULAE = [TOTAL_PRODUCT_AMOUNT]*EXCHANGE RATE  -- JUST BACKEND
	[FINAL_SALES_AMOUNT_LC] DECIMAL(15,4), -- [FINAL_PRODUCT_AMOUNT] X EXCHANGE RATE -- JUST BACK END
	REMARKS VARCHAR(2000) ,-- TEXXT
	STATUS_ENTRY VARCHAR(20) ,
	CREATED_BY VARCHAR(50) ,
	CREATED_DATE DATETIME ,
	CREATED_MAC_ADDRESS VARCHAR(50) ,
	MODIFIED_BY VARCHAR(50) ,
	MODIFIED_DATE DATETIME ,
	MODIFIED_MAC_ADDRESS VARCHAR(50) ,
	)

	GO
	
CREATE TABLE [STOENTRIES].[TBL_SALES_PROFORMA_FILES_UPLOAD](
[SNO] INT IDENTITY(1,1) CONSTRAINT PK_SI_UPLOAD_SNO PRIMARY KEY,
[SALES_PROFORMA_REF_NO] VARCHAR(50) CONSTRAINT FK_UPLOAD_SALES_PROFORMA_REF_NO FOREIGN KEY REFERENCES [STOENTRIES].[TBL_SALES_PROFORMA_HDR]([SALES_PROFORMA_REF_NO] ),
DOCUMENT_TYPE VARCHAR(50),-- DROP DOWN PROFORMA/
[DESCRIPTION_DETAILS] VARCHAR(100), -- TEXT
[FILE_NAME] VARCHAR(150), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_TYPE] VARCHAR(50), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_DATA] VARBINARY(MAX), -- AUTO FROM UPLOAD ATTACHED FILE
[REMARKS] VARCHAR(1000),-- TEXT
[STATUS_MASTER] VARCHAR(20),--
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_IP_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_IP_ADDRESS] VARCHAR(50) 
);

GO

	
CREATE TABLE [STOENTRIES].[TBL_SALES_ORDER_FILES_UPLOAD](
[SNO] INT IDENTITY(1,1) CONSTRAINT PK_SO_UPLOAD_SNO PRIMARY KEY,
[SALES_ORDER_REF_NO] VARCHAR(50) CONSTRAINT FK_UPLOAD_SO_REF_NO FOREIGN KEY REFERENCES [STOENTRIES].[TBL_SALES_ORDER_HDR]([SALES_ORDER_REF_NO]),
DOCUMENT_TYPE VARCHAR(50),-- DROP DOWN PROFORMA/
[DESCRIPTION_DETAILS] VARCHAR(100), -- TEXT
[FILE_NAME] VARCHAR(150), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_TYPE] VARCHAR(50), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_DATA] VARBINARY(MAX), -- AUTO FROM UPLOAD ATTACHED FILE
[REMARKS] VARCHAR(1000),-- TEXT
[STATUS_MASTER] VARCHAR(20),--
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_IP_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_IP_ADDRESS] VARCHAR(50) 
);

GO


	
CREATE TABLE [STOENTRIES].[TBL_DELIVERY_NOTE_FILES_UPLOAD](
[SNO] INT IDENTITY(1,1) CONSTRAINT PK_DEL_UPLOAD_SNO PRIMARY KEY,
[DELIVERY_NOTE_REF_NO] VARCHAR(50) CONSTRAINT FK_UPLOAD_SO_REF_NO FOREIGN KEY REFERENCES [STOENTRIES].[TBL_DELIVERY_NOTE_HDR](DELIVERY_NOTE_REF_NO),
DOCUMENT_TYPE VARCHAR(50),-- DROP DOWN PROFORMA/
[DESCRIPTION_DETAILS] VARCHAR(100), -- TEXT
[FILE_NAME] VARCHAR(150), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_TYPE] VARCHAR(50), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_DATA] VARBINARY(MAX), -- AUTO FROM UPLOAD ATTACHED FILE
[REMARKS] VARCHAR(1000),-- TEXT
[STATUS_MASTER] VARCHAR(20),--
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_IP_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_IP_ADDRESS] VARCHAR(50) 
);

GO

	
CREATE TABLE [STOENTRIES].[TBL_TAX_INVOICE_FILES_UPLOAD](
[SNO] INT IDENTITY(1,1) CONSTRAINT PK_TAX_UPLOAD_SNO PRIMARY KEY,
[TAX_INVOICE_REF_NO] VARCHAR(50) CONSTRAINT FK_UPLOAD_TAX_REF_NO FOREIGN KEY REFERENCES [STOENTRIES].[TBL_TAX_INVOICE_HDR](TAX_INVOICE_REF_NO),
DOCUMENT_TYPE VARCHAR(50),-- DROP DOWN PROFORMA/
[DESCRIPTION_DETAILS] VARCHAR(100), -- TEXT
[FILE_NAME] VARCHAR(150), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_TYPE] VARCHAR(50), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_DATA] VARBINARY(MAX), -- AUTO FROM UPLOAD ATTACHED FILE
[REMARKS] VARCHAR(1000),-- TEXT
[STATUS_MASTER] VARCHAR(20),--
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_IP_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_IP_ADDRESS] VARCHAR(50) 
);

go

CREATE TABLE [STOENTRIES].[TBL_SALES_ORDER_FILES_UPLOAD](
[SNO] INT IDENTITY(1,1) CONSTRAINT PK_SO_UPLOAD_SNO PRIMARY KEY,
[SALES_ORDER_REF_NO] VARCHAR(50) CONSTRAINT FK_UPLOAD_SO_REF_NO FOREIGN KEY REFERENCES [STOENTRIES].[TBL_SALES_ORDER_HDR]([SALES_ORDER_REF_NO]),
DOCUMENT_TYPE VARCHAR(50),-- DROP DOWN PROFORMA/
[DESCRIPTION_DETAILS] VARCHAR(100), -- TEXT
[FILE_NAME] VARCHAR(150), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_TYPE] VARCHAR(50), -- AUTO FROM UPLOAD ATTACHED FILE
[CONTENT_DATA] VARBINARY(MAX), -- AUTO FROM UPLOAD ATTACHED FILE
[REMARKS] VARCHAR(1000),-- TEXT
[STATUS_MASTER] VARCHAR(20),--
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_IP_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_IP_ADDRESS] VARCHAR(50) 
);

GO
