-- =============================================
-- DATABASE CREATION
-- =============================================
-- Note: In PostgreSQL, you need to create the database separately
-- CREATE DATABASE Prime;
-- \c Prime;

-- =============================================
-- SCHEMA CREATION
-- =============================================
CREATE SCHEMA IF NOT EXISTS Stomaster;
CREATE SCHEMA IF NOT EXISTS StoEntries;

-- =============================================
-- STOMASTER SCHEMA TABLES
-- =============================================

-- TBL_CUSTOMER_PAYMENT_MODE_MASTER
CREATE TABLE Stomaster.TBL_CUSTOMER_PAYMENT_MODE_MASTER (
    PAYMENT_MODE_ID SERIAL PRIMARY KEY,
    PAYMENT_MODE_NAME VARCHAR(50),
    SHORT_CODE VARCHAR(20),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_BILLING_LOCATION_MASTER
CREATE TABLE Stomaster.TBL_BILLING_LOCATION_MASTER (
    Billing_Location_Id SERIAL PRIMARY KEY,
    Billing_Location_Name VARCHAR(100) UNIQUE,
    Billing_Location_Description VARCHAR(100),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_BANK_MASTER
CREATE TABLE Stomaster.TBL_BANK_MASTER (
    BANK_ID SERIAL PRIMARY KEY,
    BANK_NAME VARCHAR(50) UNIQUE,
    ADDRESS VARCHAR(50),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_ROLE_MASTER
CREATE TABLE Stomaster.TBL_ROLE_MASTER (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) UNIQUE,
    ROLE_DESCRIPTION VARCHAR(50),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_CURRENCY_MASTER
CREATE TABLE Stomaster.TBL_CURRENCY_MASTER (
    CURRENCY_ID SERIAL PRIMARY KEY,
    CURRENCY_NAME VARCHAR(50) UNIQUE,
    ADDRESS VARCHAR(50),
    Exchange_Rate DECIMAL(15,5),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_COMPANY_MASTER
CREATE TABLE Stomaster.TBL_COMPANY_MASTER (
    Company_Id SERIAL PRIMARY KEY,
    Company_Name VARCHAR(100) UNIQUE,
    TIN_Number VARCHAR(50) UNIQUE,
    Address VARCHAR(2000),
    Contact_Person VARCHAR(50),
    Contact_Number VARCHAR(50),
    Email VARCHAR(50),
    Short_Code VARCHAR(4),
    Finance_Start_Month VARCHAR(50),
    Finance_End_Month VARCHAR(50),
    Year_Code VARCHAR(50),
    Company_Full_Name VARCHAR(150),
    Currency_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    TimeZone VARCHAR(50),
    No_Of_User INTEGER,
    WebSite VARCHAR(50),
    Comp_Big_Logo BYTEA,
    Comp_Small_Logo BYTEA,
    Comp_Letter_Head BYTEA,
    Comp_Stamp_LOGO BYTEA,
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_EXCHANGE_RATE_MASTER
CREATE TABLE Stomaster.TBL_EXCHANGE_RATE_MASTER (
    SNO SERIAL PRIMARY KEY,
    Company_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    Exchange_Rate DECIMAL(15,5),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_USER_INFO_HDR
CREATE TABLE Stomaster.TBL_USER_INFO_HDR (
    LOGIN_ID_USER_HDR SERIAL PRIMARY KEY,
    NEW_CARD_NO_USER_HDR INTEGER,
    LOGIN_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_USER_HDR VARCHAR(100),
    ROLE_USER_HDR VARCHAR(100),
    MOBILE_NO_USER_HDR VARCHAR(30),
    MAIL_ID_USER_HDR VARCHAR(150),
    STOCK_SHOW_STATUS VARCHAR(10),
    OUTSIDE_ACCESS_Y_N VARCHAR(20),
    STATUS_USER_HDR VARCHAR(20),
    REMARKS_USER_HDR VARCHAR(1000),
    CREATED_USER_USER_HDR VARCHAR(50),
    CREATED_DATE_USER_HDR TIMESTAMP,
    CREATED_MAC_ADDR_USER_HDR VARCHAR(50),
    MODIFIED_USER_USER_HDR VARCHAR(50),
    MODIFIED_DATE_USER_HDR TIMESTAMP,
    MODIFIED_MAC_ADDR_USER_HDR VARCHAR(50)
);

-- TBL_VAT_PERCENTAGE_SETTING
CREATE TABLE Stomaster.TBL_VAT_PERCENTAGE_SETTING (
    SNO SERIAL PRIMARY KEY,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    VAT_PERCENTAGE DECIMAL(15,2),
    EFFECTIVE_FROM TIMESTAMP,
    EFFECTIVE_TO TIMESTAMP,
    REMARKS VARCHAR(2000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_LOCATION_MASTER
CREATE TABLE Stomaster.TBL_LOCATION_MASTER (
    Location_Id SERIAL PRIMARY KEY,
    Location_Name VARCHAR(100) UNIQUE,
    Location_Description VARCHAR(100),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_STORE_MASTER
CREATE TABLE Stomaster.TBL_STORE_MASTER (
    Store_Id SERIAL PRIMARY KEY,
    Store_Name VARCHAR(100) UNIQUE,
    Location_Id INTEGER REFERENCES Stomaster.TBL_LOCATION_MASTER(Location_Id),
    Manager_Name VARCHAR(50),
    Store_Short_Code VARCHAR(5),
    Store_Short_Name VARCHAR(100),
    Email_Address VARCHAR(1000),
    CC_Email_Address TEXT,
    BCC_Email_Address VARCHAR(50),
    Response_Directors_Name VARCHAR(1000),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_USER_TO_STORE_MAPPING
CREATE TABLE Stomaster.TBL_USER_TO_STORE_MAPPING (
    USER_TO_LOCATION_ID_USER_TO_ROLE SERIAL PRIMARY KEY,
    USER_ID_USER_TO_ROLE INTEGER REFERENCES Stomaster.TBL_USER_INFO_HDR(LOGIN_ID_USER_HDR),
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    STORE_ID_USER_TO_ROLE INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    ROLE_ID_USER_TO_ROLE INTEGER REFERENCES Stomaster.TBL_ROLE_MASTER(ROLE_ID),
    STATUS_USER_TO_ROLE VARCHAR(20),
    CREATED_USER_USER_TO_ROLE VARCHAR(50),
    CREATED_DATE_USER_TO_ROLE TIMESTAMP,
    CREATED_MAC_ADDR_USER_TO_ROLE VARCHAR(50),
    MODIFIED_USER_USER_TO_ROLE VARCHAR(50),
    MODIFIED_DATE_USER_TO_ROLE TIMESTAMP,
    MODIFIED_MAC_ADDR_USER_TO_ROLE VARCHAR(50)
);

-- TBL_PAYMENT_MODE_MASTER
CREATE TABLE Stomaster.TBL_PAYMENT_MODE_MASTER (
    PAYMENT_MODE_ID SERIAL PRIMARY KEY,
    PAYMENT_MODE_NAME VARCHAR(50) UNIQUE,
    PAYMENT_MODE_PERCENTAGE DECIMAL(15,2),
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_ADDITIONAL_COST_TYPE_MASTER
CREATE TABLE Stomaster.TBL_ADDITIONAL_COST_TYPE_MASTER (
    ADDITIONAL_COST_TYPE_ID SERIAL PRIMARY KEY,
    ADDITIONAL_COST_TYPE_NAME VARCHAR(50) UNIQUE,
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_PAYMENT_TERM_MASTER
CREATE TABLE Stomaster.TBL_PAYMENT_TERM_MASTER (
    PAYMENT_TERM_ID SERIAL PRIMARY KEY,
    PAYMENT_TERM_NAME VARCHAR(50) UNIQUE,
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_ACCOUNTS_LEDGER_GROUP_MASTER
CREATE TABLE Stomaster.TBL_ACCOUNTS_LEDGER_GROUP_MASTER (
    LEDGER_GROUP_ID SERIAL PRIMARY KEY,
    LEDGER_GROUP_NAME VARCHAR(50) UNIQUE,
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_ACCOUNTS_HEAD_MASTER
CREATE TABLE Stomaster.TBL_ACCOUNTS_HEAD_MASTER (
    ACCOUNT_HEAD_ID SERIAL PRIMARY KEY,
    ACCOUNT_HEAD_NAME VARCHAR(50) UNIQUE,
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_PRODUCT_MAIN_CATEGORY_MASTER
CREATE TABLE Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER (
    MAIN_CATEGORY_ID SERIAL PRIMARY KEY,
    MAIN_CATEGORY_NAME VARCHAR(100) UNIQUE,
    REMARKS VARCHAR(2000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_PRODUCT_SUB_CATEGORY_MASTER
CREATE TABLE Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER (
    SUB_CATEGORY_ID SERIAL PRIMARY KEY,
    SUB_CATEGORY_NAME VARCHAR(50) UNIQUE,
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    REMARKS VARCHAR(2000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_PRODUCT_MASTER
CREATE TABLE Stomaster.TBL_PRODUCT_MASTER (
    PRODUCT_ID SERIAL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(150) UNIQUE,
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    UOM VARCHAR(50),
    QTY_PER_PACKING DECIMAL(15,2),
    ALTERNATE_UOM VARCHAR(50),
    REMARKS VARCHAR(2000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_COUNTRY_MASTER
CREATE TABLE Stomaster.TBL_COUNTRY_MASTER (
    Country_Id SERIAL PRIMARY KEY,
    Country_Name VARCHAR(100) UNIQUE,
    nicename VARCHAR(80),
    iso3 VARCHAR(50),
    numcode INTEGER,
    phonecode INTEGER,
    Batch_No VARCHAR(2),
    Remarks VARCHAR(1000),
    Status_Master VARCHAR(50),
    Created_User VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_User VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_REGION_MASTER
CREATE TABLE Stomaster.TBL_REGION_MASTER (
    REGION_ID SERIAL PRIMARY KEY,
    REGION_NAME VARCHAR(50) UNIQUE,
    COUNTRY_ID INTEGER REFERENCES Stomaster.TBL_COUNTRY_MASTER(Country_Id),
    CAPITAL VARCHAR(50),
    NO_OF_DISTRICTS INTEGER,
    TOTAL_POPULATION DECIMAL(18,2),
    ZONE_NAME VARCHAR(50),
    DISTANCE_FROM_ARUSHA DECIMAL(18,2),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_PRODUCT_OPENING_STOCK
CREATE TABLE Stomaster.TBL_PRODUCT_OPENING_STOCK (
    SNO SERIAL PRIMARY KEY,
    OPENING_STOCK_DATE TIMESTAMP,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    TOTAL_QTY DECIMAL(15,2),
    REMARKS VARCHAR(2000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_FIELD_HDR
CREATE TABLE Stomaster.TBL_FIELD_HDR (
    field_id_fld_hdr BIGSERIAL PRIMARY KEY,
    project_name_fld_hdr VARCHAR(50),
    field_category_fld_hdr VARCHAR(50) UNIQUE,
    field_desc_fld_hdr VARCHAR(150),
    status_fld_hdr VARCHAR(20),
    remarks_fld_hdr VARCHAR(1000),
    created_user_fld_hdr VARCHAR(50),
    created_date_fld_hdr TIMESTAMP,
    created_mac_addr_fld_hdr VARCHAR(50),
    modified_user_fld_hdr VARCHAR(50),
    modified_date_fld_hdr TIMESTAMP,
    modified_mac_addr_fld_hdr VARCHAR(50)
);

-- TBL_FIELD_DTL
CREATE TABLE Stomaster.TBL_FIELD_DTL (
    activity_id_fld_dtl BIGSERIAL PRIMARY KEY,
    field_id_fld_dtl BIGINT REFERENCES Stomaster.TBL_FIELD_HDR(field_id_fld_hdr),
    activity_name_fld_dtl TEXT,
    activity_desc_fld_dtl TEXT,
    status_fld_dtl VARCHAR(10),
    remarks_fld_dtl VARCHAR(1000),
    created_user_fld_dtl VARCHAR(50),
    created_date_fld_dtl TIMESTAMP,
    created_mac_addr_fld_dtl VARCHAR(50),
    modified_user_fld_dtl VARCHAR(50),
    modified_date_fld_dtl TIMESTAMP,
    modified_mac_addr_fld_dtl VARCHAR(50)
);

-- TBL_PRODUCT_COMPANY_MAIN_CATEGORY_MAPPING
CREATE TABLE Stomaster.TBL_PRODUCT_COMPANY_MAIN_CATEGORY_MAPPING (
    Sno SERIAL PRIMARY KEY,
    Company_Id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Main_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_STORE_PRODUCT_MINIMUM_STOCK
CREATE TABLE Stomaster.TBL_STORE_PRODUCT_MINIMUM_STOCK (
    Sno SERIAL PRIMARY KEY,
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Store_Id INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    Main_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    Sub_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    Product_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    Minimum_Stock_Pcs INTEGER,
    Purchase_Alert_Qty DECIMAL(15,2),
    Requested_By VARCHAR(50),
    Effective_From TIMESTAMP,
    Effective_To TIMESTAMP,
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_SUPPLIER_MASTER
CREATE TABLE Stomaster.TBL_SUPPLIER_MASTER (
    Supplier_Id SERIAL PRIMARY KEY,
    Supplier_Type VARCHAR(50),
    Supplier_Name VARCHAR(250) UNIQUE,
    TIN_Number VARCHAR(100),
    Vat_Register_No VARCHAR(50),
    SH_Nick_Name VARCHAR(50),
    Shipment_Mode VARCHAR(100),
    Country_Id INTEGER REFERENCES Stomaster.TBL_COUNTRY_MASTER(Country_Id),
    Region_Id INTEGER,
    District_Id INTEGER,
    Address VARCHAR(2500),
    Contact_Person VARCHAR(50),
    Phone_number VARCHAR(50),
    Mail_Id VARCHAR(50),
    Fax VARCHAR(50),
    vat_Percentage DECIMAL(15,2),
    Withholding_vat_percentage DECIMAL(15,2),
    Remarks VARCHAR(150),
    Status_Master VARCHAR(20),
    Created_User VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_User VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_COMPANY_BANK_ACCOUNT_MASTER
CREATE TABLE Stomaster.TBL_COMPANY_BANK_ACCOUNT_MASTER (
    Account_Id SERIAL PRIMARY KEY,
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Bank_Id INTEGER REFERENCES Stomaster.TBL_BANK_MASTER(BANK_ID),
    Account_Name VARCHAR(100) UNIQUE,
    Account_Number VARCHAR(100) UNIQUE,
    Swift_Code VARCHAR(50),
    Branch_Address VARCHAR(200),
    Bank_Branch_Name VARCHAR(50),
    Currency_Id INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_CHANGE_PASSWORD_LOG
CREATE TABLE Stomaster.TBL_CHANGE_PASSWORD_LOG (
    Sno SERIAL PRIMARY KEY,
    login_id INTEGER REFERENCES Stomaster.TBL_USER_INFO_HDR(LOGIN_ID_USER_HDR),
    User_Name VARCHAR(50),
    Old_Password VARCHAR(50),
    New_Password VARCHAR(50),
    Reason VARCHAR(1000),
    status_entry VARCHAR(50),
    Created_by VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_by VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_DISTRICT_MASTER
CREATE TABLE Stomaster.TBL_DISTRICT_MASTER (
    District_id SERIAL PRIMARY KEY,
    Country_Id INTEGER REFERENCES Stomaster.TBL_COUNTRY_MASTER(Country_Id),
    Region_Id INTEGER REFERENCES Stomaster.TBL_REGION_MASTER(REGION_ID),
    District_Name VARCHAR(50),
    Total_Population DECIMAL(18,2),
    Zone_Name VARCHAR(50),
    Distance_From_Arusha DECIMAL(18,2),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_CUSTOMER_MASTER
CREATE TABLE Stomaster.TBL_CUSTOMER_MASTER (
    Customer_Id SERIAL PRIMARY KEY,
    Customer_Name VARCHAR(250) UNIQUE,
    TIN_Number VARCHAR(100),
    VAT_Number VARCHAR(50),
    Contact_Person VARCHAR(50),
    Contact_Number VARCHAR(50),
    Location VARCHAR(100),
    Nature_Of_Business VARCHAR(50),
    Billing_Location_Id INTEGER REFERENCES Stomaster.TBL_BILLING_LOCATION_MASTER(Billing_Location_Id),
    Country_Id INTEGER REFERENCES Stomaster.TBL_COUNTRY_MASTER(Country_Id),
    Region_Id INTEGER REFERENCES Stomaster.TBL_REGION_MASTER(REGION_ID),
    District_Id INTEGER REFERENCES Stomaster.TBL_DISTRICT_MASTER(District_id),
    currency_id INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    CREDIT_ALLOWED VARCHAR(50),
    Address VARCHAR(1500),
    Email_Address VARCHAR(100),
    PHONE_NUMBER_2 VARCHAR(50),
    LAT DECIMAL(15,9),
    LNG DECIMAL(15,9),
    TIER VARCHAR(50),
    Company_Head_Contact_Person VARCHAR(250),
    Company_Head_Phone_No VARCHAR(250),
    Company_Head_Email VARCHAR(250),
    Accounts_Contact_Person VARCHAR(250),
    Accounts_Phone_No VARCHAR(250),
    Accounts_Email VARCHAR(250),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_CUSTOMER_ADDRESS_DETAILS
CREATE TABLE Stomaster.TBL_CUSTOMER_ADDRESS_DETAILS (
    Sno SERIAL PRIMARY KEY,
    Customer_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    Address_Count INTEGER,
    Contact_Person VARCHAR(50),
    Contact_Number VARCHAR(50),
    Address VARCHAR(5000),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_CUSTOMER_MASTER_FILES_UPLOAD
CREATE TABLE Stomaster.TBL_CUSTOMER_MASTER_FILES_UPLOAD (
    SNO SERIAL PRIMARY KEY,
    Customer_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    DOCUMENT_TYPE VARCHAR(50),
    DESCRIPTIONS VARCHAR(100),
    FILE_NAME VARCHAR(150),
    CONTENT_TYPE VARCHAR(50),
    CONTENT_DATA BYTEA,
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_CUSTOMER_COMPANY_WISE_BILLING_LOCATION_MAPPING
CREATE TABLE Stomaster.TBL_CUSTOMER_COMPANY_WISE_BILLING_LOCATION_MAPPING (
    SNO SERIAL PRIMARY KEY,
    Customer_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Billing_Location_Id INTEGER REFERENCES Stomaster.TBL_BILLING_LOCATION_MASTER(Billing_Location_Id),
    EFFECTIVE_FROM TIMESTAMP,
    EFFECTIVE_TO TIMESTAMP,
    REMARKS VARCHAR(500),
    STATUS_MASTER VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_CUSTOMER_PRODUCT_VAT_PERCENTAGE_SETTINGS
CREATE TABLE Stomaster.TBL_CUSTOMER_PRODUCT_VAT_PERCENTAGE_SETTINGS (
    SNO SERIAL PRIMARY KEY,
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Customer_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    Main_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    Sub_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    Product_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    VAT_PERCENTAGE DECIMAL(10,2),
    EFFECTIVE_FROM TIMESTAMP,
    EFFECTIVE_TO TIMESTAMP,
    REQUEST_STATUS VARCHAR(50),
    REMARKS VARCHAR(100),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_CUSTOMER_WISE_PRODUCT_PRICE_SETTINGS
CREATE TABLE Stomaster.TBL_CUSTOMER_WISE_PRODUCT_PRICE_SETTINGS (
    Sno SERIAL PRIMARY KEY,
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Customer_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    Main_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    Sub_Category_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    Product_Id INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    VAT_Percentage DECIMAL(15,2),
    Valid_Type VARCHAR(50),
    currency_id INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    Effective_From TIMESTAMP,
    Effective_To TIMESTAMP,
    Requested_By VARCHAR(50),
    Requested_Date TIMESTAMP,
    Requested_Product_Amount DECIMAL(15,4),
    Approved_Product_Amount DECIMAL(15,4),
    Respond_By VARCHAR(50),
    Response_Status VARCHAR(50),
    REspond_Date TIMESTAMP,
    Respond_Mac_Address VARCHAR(50),
    Response_Remarks VARCHAR(1000),
    Accounts_Response_Person VARCHAR(50),
    Accounts_Response_Date TIMESTAMP,
    Accounts_Response_Status VARCHAR(50),
    Accounts_Response_Remarks VARCHAR(500),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- TBL_CUSTOMER_CREDIT_LIMIT_DETAILS
CREATE TABLE Stomaster.TBL_CUSTOMER_CREDIT_LIMIT_DETAILS (
    Sno SERIAL PRIMARY KEY,
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    Customer_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    Currency_id INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    Valid_Type VARCHAR(50),
    Requested_Credit_Limit_Days INTEGER,
    Requested_Credit_Limit_Amount DECIMAL(15,2),
    Requested_Payment_Mode_Id INTEGER REFERENCES Stomaster.TBL_CUSTOMER_PAYMENT_MODE_MASTER(PAYMENT_MODE_ID),
    Requested_By VARCHAR(50),
    Requested_Date TIMESTAMP,
    Total_Outstanding_Amount DECIMAL(15,2),
    Over_Due_Outstanding_Amount DECIMAL(15,2),
    Approved_Credit_Limit_Days INTEGER,
    Approved_Credit_Limit_Amount DECIMAL(15,2),
    Approved_PAYMENT_MODE_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_PAYMENT_MODE_MASTER(PAYMENT_MODE_ID),
    Effective_From TIMESTAMP,
    Effective_To TIMESTAMP,
    Finance_Head_1_Response_By VARCHAR(50),
    Finance_Head_1_Response_Date TIMESTAMP,
    Finance_Head_1_Response_Status VARCHAR(50),
    Finance_Head_1_Response_IP_Address VARCHAR(50),
    Finance_Head_1_Response_Remarks VARCHAR(500),
    Respond_by VARCHAR(50),
    Respond_Status VARCHAR(50),
    Respond_Date TIMESTAMP,
    Respond_Mac_address VARCHAR(50),
    Response_Remarks VARCHAR(1000),
    Remarks VARCHAR(2000),
    Status_Master VARCHAR(20),
    Created_By VARCHAR(50),
    Created_Date TIMESTAMP,
    Created_Mac_Address VARCHAR(50),
    Modified_By VARCHAR(50),
    Modified_Date TIMESTAMP,
    Modified_Mac_Address VARCHAR(50)
);

-- CUSTOMER_CREDIT_LIMIT_FILE_UPLOAD
CREATE TABLE Stomaster.CUSTOMER_CREDIT_LIMIT_FILE_UPLOAD (
    SNO SERIAL PRIMARY KEY,
    CREDIT_LIMIT_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_CREDIT_LIMIT_DETAILS(Sno),
    DESCRIPTION_DETAILS VARCHAR(100),
    FILE_NAME VARCHAR(150),
    CONTENT_TYPE VARCHAR(50),
    CONTENT_DATA BYTEA,
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50),
    Document_Type VARCHAR(60)
);

-- TBL_ACCOUNTS_LEDGER_MASTER
CREATE TABLE Stomaster.TBL_ACCOUNTS_LEDGER_MASTER (
    LEDGER_ID SERIAL PRIMARY KEY,
    Company_id INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    LEDGER_TYPE VARCHAR(50),
    LEDGER_GROUP_ID INTEGER,
    LEDGER_NAME VARCHAR(100),
    LEDGER_DESC VARCHAR(100),
    REMARKS VARCHAR(100),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_SALES_PERSON_MASTER
CREATE TABLE Stomaster.TBL_SALES_PERSON_MASTER (
    Sales_Person_ID SERIAL PRIMARY KEY,
    Emp_Id INTEGER,
    PERSON_NAME VARCHAR(50),
    Designation_Name VARCHAR(50),
    Sales_Contact_Person_Phone VARCHAR(60),
    Sales_Person_Email_Addres VARCHAR(60),
    Reporting_Manager_Card_No INTEGER,
    Reporting_Manager_Name VARCHAR(100),
    Reporting_Manager_Email_Address VARCHAR(100),
    Sales_Person_Designation VARCHAR(100),
    REMARKS VARCHAR(50),
    STATUS_MASTER VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- =============================================
-- STOENTRIES SCHEMA TABLES
-- =============================================

-- TBL_PURCHASE_ORDER_HDR
CREATE TABLE StoEntries.TBL_PURCHASE_ORDER_HDR (
    SNO SERIAL,
    PO_REF_NO VARCHAR(50) PRIMARY KEY,
    PO_DATE TIMESTAMP,
    PURCHASE_TYPE VARCHAR(20),
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    SUPPLIER_ID INTEGER REFERENCES Stomaster.TBL_SUPPLIER_MASTER(Supplier_Id),
    PO_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    PAYMENT_TERM_ID INTEGER REFERENCES Stomaster.TBL_PAYMENT_TERM_MASTER(PAYMENT_TERM_ID),
    MODE_OF_PAYMENT VARCHAR(25),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    SUPLIER_PROFORMA_NUMBER VARCHAR(100),
    SHIPMENT_MODE VARCHAR(100),
    PRICE_TERMS VARCHAR(150),
    ESTIMATED_SHIPMENT_DATE TIMESTAMP,
    SHIPMENT_REMARKS VARCHAR(2500),
    PRODUCT_HDR_AMOUNT DECIMAL(15,4),
    TOTAL_ADDITIONAL_COST_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_HDR_AMOUNT DECIMAL(15,4),
    TOTAL_VAT_HDR_AMOUNT DECIMAL(15,2),
    FINAL_PURCHASE_HDR_AMOUNT DECIMAL(15,2),
    EXCHANGE_RATE DECIMAL(10,2),
    PRODUCT_HDR_AMOUNT_LC DECIMAL(15,4),
    TOTAL_ADDITIONAL_COST_AMOUNT_LC DECIMAL(15,4),
    TOTAL_PRODUCT_HDR_AMOUNT_LC DECIMAL(15,4),
    TOTAL_VAT_HDR_AMOUNT_LC DECIMAL(15,2),
    FINAL_PURCHASE_HDR_AMOUNT_LC DECIMAL(15,2),
    SUBMITTED_BY VARCHAR(50),
    SUBMITTED_DATE TIMESTAMP,
    SUBMITTED_IP_ADDRESS VARCHAR(50),
    PURCHASE_HEAD_RESPONSE_PERSON VARCHAR(50),
    PURCHASE_HEAD_RESPONSE_DATE TIMESTAMP,
    PURCHASE_HEAD_RESPONSE_STATUS VARCHAR(50),
    PURCHASE_HEAD_RESPONSE_REMARKS VARCHAR(500),
    PURCHASE_HEAD_RESPONSE_IP_ADDRESS VARCHAR(50),
    RESPONSE_1_PERSON VARCHAR(50),
    RESPONSE_1_DATE TIMESTAMP,
    RESPONSE_1_STATUS VARCHAR(50),
    RESPONSE_1_REMARKS VARCHAR(5000),
    RESPONSE_1_IP_ADDRESS VARCHAR(50),
    RESPONSE_2_PERSON VARCHAR(50),
    RESPONSE_2_DATE TIMESTAMP,
    RESPONSE_2_STATUS VARCHAR(50),
    RESPONSE_2_REMARKS VARCHAR(5000),
    RESPONSE_2_IP_ADDRESS VARCHAR(50),
    FINAL_RESPONSE_PERSON VARCHAR(50),
    FINAL_RESPONSE_DATE TIMESTAMP,
    FINAL_RESPONSE_STATUS VARCHAR(50),
    FINAL_RESPONSE_REMARKS VARCHAR(5000),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_ORDER_DTL
CREATE TABLE StoEntries.TBL_PURCHASE_ORDER_DTL (
    SNO SERIAL PRIMARY KEY,
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    REQUEST_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    QTY_PER_PACKING DECIMAL(15,2),
    TOTAL_QTY DECIMAL(15,4),
    UOM VARCHAR(50),
    TOTAL_PACKING DECIMAL(15,4),
    ALTERNATE_UOM VARCHAR(500),
    RATE_PER_QTY DECIMAL(15,6),
    PRODUCT_AMOUNT DECIMAL(15,4),
    DISCOUNT_PERCENTAGE DECIMAL(15,2),
    DISCOUNT_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_PERCENTAGE DECIMAL(15,2),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_PRODUCT_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS
CREATE TABLE StoEntries.TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS (
    SNO SERIAL PRIMARY KEY,
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    ADDITIONAL_COST_TYPE_ID INTEGER REFERENCES Stomaster.TBL_ADDITIONAL_COST_TYPE_MASTER(ADDITIONAL_COST_TYPE_ID),
    ADDITIONAL_COST_AMOUNT DECIMAL(15,4),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_ORDER_FILES_UPLOAD
CREATE TABLE StoEntries.TBL_PURCHASE_ORDER_FILES_UPLOAD (
    SNO SERIAL PRIMARY KEY,
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    DOCUMENT_TYPE VARCHAR(50),
    DESCRIPTION_DETAILS VARCHAR(100),
    FILE_NAME VARCHAR(150),
    CONTENT_TYPE VARCHAR(50),
    CONTENT_DATA BYTEA,
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_ORDER_CONVERSATION_DTL
CREATE TABLE StoEntries.TBL_PURCHASE_ORDER_CONVERSATION_DTL (
    SNO SERIAL PRIMARY KEY,
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    RESPOND_PERSON VARCHAR(50),
    DISCUSSION_DETAILS TEXT,
    RESPONSE_STATUS VARCHAR(50),
    STATUS_ENTRY VARCHAR(50),
    REMARKS VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_GOODS_INWARD_GRN_HDR
CREATE TABLE StoEntries.TBL_GOODS_INWARD_GRN_HDR (
    SNO SERIAL,
    GRN_REF_NO VARCHAR(50) PRIMARY KEY,
    GRN_DATE TIMESTAMP,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    SOURCE_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    GRN_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    GRN_SOURCE VARCHAR(50),
    DELIVERY_NOTE_REF_NO VARCHAR(50),
    SUPPLIER_ID INTEGER REFERENCES Stomaster.TBL_SUPPLIER_MASTER(Supplier_Id),
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    PURCHASE_INVOICE_REF_NO VARCHAR(50),
    SUPPLIER_INVOICE_NUMBER VARCHAR(100),
    CONTAINER_NO VARCHAR(20),
    DRIVER_NAME VARCHAR(50),
    DRIVER_CONTACT_NUMBER VARCHAR(50),
    VEHICLE_NO VARCHAR(50),
    SEAL_NO VARCHAR(50),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_GOODS_INWARD_GRN_DTL
CREATE TABLE StoEntries.TBL_GOODS_INWARD_GRN_DTL (
    SNO SERIAL PRIMARY KEY,
    GRN_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_GOODS_INWARD_GRN_HDR(GRN_REF_NO),
    PO_DTL_SNO INTEGER REFERENCES StoEntries.TBL_PURCHASE_ORDER_DTL(SNO),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    QTY_PER_PACKING DECIMAL(15,2),
    TOTAL_QTY DECIMAL(15,4),
    UOM VARCHAR(50),
    TOTAL_PACKING DECIMAL(15,4),
    ALTERNATE_UOM VARCHAR(500),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_INVOICE_HDR
CREATE TABLE StoEntries.TBL_PURCHASE_INVOICE_HDR (
    SNO SERIAL,
    PURCHASE_INVOICE_REF_NO VARCHAR(50) PRIMARY KEY,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    INVOICE_NO VARCHAR(100),
    INVOICE_DATE TIMESTAMP,
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    PURCHASE_TYPE VARCHAR(20),
    SUPPLIER_ID INTEGER REFERENCES Stomaster.TBL_SUPPLIER_MASTER(Supplier_Id),
    STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    PAYMENT_TERM_ID INTEGER REFERENCES Stomaster.TBL_PAYMENT_TERM_MASTER(PAYMENT_TERM_ID),
    MODE_OF_PAYMENT VARCHAR(25),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    PRICE_TERMS VARCHAR(150),
    PRODUCT_HDR_AMOUNT DECIMAL(15,4),
    TOTAL_ADDITIONAL_COST_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_HDR_AMOUNT DECIMAL(15,4),
    TOTAL_VAT_HDR_AMOUNT DECIMAL(15,2),
    FINAL_INVOICE_HDR_AMOUNT DECIMAL(15,2),
    EXCHANGE_RATE DECIMAL(10,2),
    PRODUCT_HDR_AMOUNT_LC DECIMAL(15,4),
    TOTAL_ADDITIONAL_COST_AMOUNT_LC DECIMAL(15,4),
    TOTAL_PRODUCT_HDR_AMOUNT_LC DECIMAL(15,4),
    TOTAL_VAT_HDR_AMOUNT_LC DECIMAL(15,2),
    FINAL_PURCHASE_INVOICE_AMOUNT_LC DECIMAL(15,2),
    SUBMITTED_BY VARCHAR(50),
    SUBMITTED_DATE TIMESTAMP,
    SUBMITTED_IP_ADDRESS VARCHAR(50),
    RESPONSE_1_PERSON VARCHAR(50),
    RESPONSE_1_DATE TIMESTAMP,
    RESPONSE_1_STATUS VARCHAR(50),
    RESPONSE_1_REMARKS VARCHAR(5000),
    RESPONSE_1_IP_ADDRESS VARCHAR(50),
    RESPONSE_2_PERSON VARCHAR(50),
    RESPONSE_2_DATE TIMESTAMP,
    RESPONSE_2_STATUS VARCHAR(50),
    RESPONSE_2_REMARKS VARCHAR(5000),
    RESPONSE_2_IP_ADDRESS VARCHAR(50),
    FINAL_RESPONSE_PERSON VARCHAR(50),
    FINAL_RESPONSE_DATE TIMESTAMP,
    FINAL_RESPONSE_STATUS VARCHAR(50),
    FINAL_RESPONSE_REMARKS VARCHAR(5000),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_INVOICE_DTL
CREATE TABLE StoEntries.TBL_PURCHASE_INVOICE_DTL (
    SNO SERIAL PRIMARY KEY,
    PURCHASE_INVOICE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    GRN_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_GOODS_INWARD_GRN_HDR(GRN_REF_NO),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    QTY_PER_PACKING DECIMAL(15,2),
    TOTAL_QTY DECIMAL(15,4),
    UOM VARCHAR(50),
    TOTAL_PACKING DECIMAL(15,4),
    ALTERNATE_UOM VARCHAR(500),
    RATE_PER_QTY DECIMAL(15,6),
    PRODUCT_AMOUNT DECIMAL(15,4),
    DISCOUNT_PERCENTAGE DECIMAL(15,2),
    DISCOUNT_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_PERCENTAGE DECIMAL(15,2),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_PRODUCT_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS
CREATE TABLE StoEntries.TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS (
    SNO SERIAL PRIMARY KEY,
    PURCHASE_INVOICE_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    ADDITIONAL_COST_TYPE_ID INTEGER REFERENCES Stomaster.TBL_ADDITIONAL_COST_TYPE_MASTER(ADDITIONAL_COST_TYPE_ID),
    ADDITIONAL_COST_AMOUNT DECIMAL(15,4),
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(50),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_PURCHASE_INVOICE_FILES_UPLOAD
CREATE TABLE StoEntries.TBL_PURCHASE_INVOICE_FILES_UPLOAD (
    SNO SERIAL PRIMARY KEY,
    PURCHASE_INVOICE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    DOCUMENT_TYPE VARCHAR(50),
    DESCRIPTION_DETAILS VARCHAR(100),
    FILE_NAME VARCHAR(150),
    CONTENT_TYPE VARCHAR(50),
    CONTENT_DATA BYTEA,
    REMARKS VARCHAR(1000),
    STATUS_MASTER VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_EXPENSE_HDR
CREATE TABLE StoEntries.TBL_EXPENSE_HDR (
    SNO SERIAL,
    EXPENSE_REF_NO VARCHAR(50) PRIMARY KEY,
    EXPENSE_DATE TIMESTAMP,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    EXPENSE_AGAINST VARCHAR(50),
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    ACCOUNT_HEAD_ID INTEGER REFERENCES Stomaster.TBL_ACCOUNTS_HEAD_MASTER(ACCOUNT_HEAD_ID),
    EXPENSE_SUPPLIER_ID INTEGER REFERENCES Stomaster.TBL_SUPPLIER_MASTER(Supplier_Id),
    EXPENSE_TYPE VARCHAR(100),
    TRA_EFD_RECEIPT_NO VARCHAR(100),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    EXCHANGE_RATE DECIMAL(15,2),
    TOTAL_EXPENSE_AMOUNT DECIMAL(18,2),
    TOTAL_EXPENSE_AMOUNT_LC DECIMAL(18,2),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50),
    SUBMITTED_BY VARCHAR(50),
    SUBMITTED_DATE TIMESTAMP,
    SUBMITTED_IP_ADDRESS VARCHAR(50)
);

-- TBL_EXPENSE_DTL
CREATE TABLE StoEntries.TBL_EXPENSE_DTL (
    SNO SERIAL PRIMARY KEY,
    EXPENSE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_EXPENSE_HDR(EXPENSE_REF_NO),
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    PO_DTL_SNO INTEGER REFERENCES StoEntries.TBL_PURCHASE_ORDER_DTL(SNO),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    EXPENSE_AMOUNT DECIMAL(18,2),
    EXPENSE_AMOUNT_LC DECIMAL(18,2),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_IP_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_IP_ADDRESS VARCHAR(50)
);

-- TBL_SALES_ORDER_HDR
CREATE TABLE StoEntries.TBL_SALES_ORDER_HDR (
    SNO SERIAL,
    SALES_ORDER_REF_NO VARCHAR(50) PRIMARY KEY,
    SALES_ORDER_DATE TIMESTAMP,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    CUSTOMER_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    BILLING_LOCATION_ID INTEGER REFERENCES Stomaster.TBL_BILLING_LOCATION_MASTER(Billing_Location_Id),
    SALES_PERSON_EMP_ID INTEGER REFERENCES Stomaster.TBL_SALES_PERSON_MASTER(Sales_Person_ID),
    CREDIT_LIMIT_AMOUNT DECIMAL(15,2),
    CREDIT_LIMIT_DAYS DECIMAL(15,2),
    OUTSTANDING_AMOUNT DECIMAL(15,2),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    EXCHANGE_RATE DECIMAL(15,2),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_SALES_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_SALES_AMOUNT_LC DECIMAL(15,4),
    REMARKS VARCHAR(2000),
    TEST_DESC VARCHAR(50) DEFAULT 'NA',
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50),
    SUBMITTED_BY VARCHAR(50),
    SUBMITTED_DATE TIMESTAMP
);

-- TBL_SALES_ORDER_DTL
CREATE TABLE StoEntries.TBL_SALES_ORDER_DTL (
    SNO SERIAL PRIMARY KEY,
    SALES_ORDER_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_SALES_ORDER_HDR(SALES_ORDER_REF_NO),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    STORE_STOCK_PCS DECIMAL(15,4),
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    PO_DTL_SNO INTEGER REFERENCES StoEntries.TBL_PURCHASE_ORDER_DTL(SNO),
    PO_DTL_STOCK_QTY DECIMAL(15,4),
    PURCHASE_RATE_PER_QTY DECIMAL(15,6),
    PO_EXPENSE_AMOUNT DECIMAL(15,4),
    SALES_RATE_PER_QTY DECIMAL(15,6),
    QTY_PER_PACKING DECIMAL(15,2),
    TOTAL_QTY DECIMAL(15,4),
    UOM VARCHAR(50),
    TOTAL_PACKING DECIMAL(15,4),
    ALTERNATE_UOM VARCHAR(500),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_PERCENTAGE DECIMAL(15,2),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_SALES_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_SALES_AMOUNT_LC DECIMAL(15,4),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_DELIVERY_NOTE_HDR
CREATE TABLE StoEntries.TBL_DELIVERY_NOTE_HDR (
    SNO SERIAL,
    DELIVERY_NOTE_REF_NO VARCHAR(50) PRIMARY KEY,
    DELIVERY_DATE TIMESTAMP,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    FROM_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    DELIVERY_SOURCE_TYPE VARCHAR(50),
    DELIVERY_SOURCE_REF_NO VARCHAR(50),
    TO_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    CUSTOMER_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    TRUCK_NO VARCHAR(50),
    TRAILER_NO VARCHAR(50),
    DRIVER_NAME VARCHAR(50),
    DRIVER_CONTACT_NUMBER VARCHAR(50),
    SEAL_NO VARCHAR(50),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    EXCHANGE_RATE DECIMAL(15,2),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_SALES_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_SALES_AMOUNT_LC DECIMAL(15,4),
    TEST_DESC VARCHAR(50),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50),
    SUBMITTED_BY VARCHAR(50),
    SUBMITTED_DATE TIMESTAMP,
    SUBMITTED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_DELIVERY_NOTE_DTL
CREATE TABLE StoEntries.TBL_DELIVERY_NOTE_DTL (
    SNO SERIAL PRIMARY KEY,
    DELIVERY_NOTE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_DELIVERY_NOTE_HDR(DELIVERY_NOTE_REF_NO),
    SALES_ORDER_DTL_SNO INTEGER,
    PO_DTL_SNO INTEGER REFERENCES StoEntries.TBL_PURCHASE_ORDER_DTL(SNO),
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    SALES_RATE_PER_QTY DECIMAL(15,6),
    QTY_PER_PACKING DECIMAL(15,2),
    REQUEST_QTY DECIMAL(15,4),
    DELIVERY_QTY DECIMAL(15,4),
    UOM VARCHAR(50),
    TOTAL_PACKING DECIMAL(15,4),
    ALTERNATE_UOM VARCHAR(500),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_PERCENTAGE DECIMAL(15,2),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_SALES_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_SALES_AMOUNT_LC DECIMAL(15,4),
    STORE_STOCK_PCS DECIMAL(15,2),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_TAX_INVOICE_HDR
CREATE TABLE StoEntries.TBL_TAX_INVOICE_HDR (
    SNO SERIAL,
    TAX_INVOICE_REF_NO VARCHAR(50) PRIMARY KEY,
    INVOICE_DATE TIMESTAMP,
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    FROM_STORE_ID INTEGER REFERENCES Stomaster.TBL_STORE_MASTER(Store_Id),
    INVOICE_TYPE VARCHAR(50),
    DELIVERY_NOTE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_DELIVERY_NOTE_HDR(DELIVERY_NOTE_REF_NO),
    CUSTOMER_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    EXCHANGE_RATE DECIMAL(15,2),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_SALES_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_SALES_AMOUNT_LC DECIMAL(15,4),
    TEST_DESC VARCHAR(50),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50),
    SUBMITTED_BY VARCHAR(50),
    SUBMITTED_DATE TIMESTAMP,
    SUBMITTED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_TAX_INVOICE_DTL
CREATE TABLE StoEntries.TBL_TAX_INVOICE_DTL (
    SNO SERIAL PRIMARY KEY,
    TAX_INVOICE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_TAX_INVOICE_HDR(TAX_INVOICE_REF_NO),
    DELIVERY_NOTE_DTL_SNO INTEGER,
    PO_DTL_SNO INTEGER REFERENCES StoEntries.TBL_PURCHASE_ORDER_DTL(SNO),
    PO_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_PURCHASE_ORDER_HDR(PO_REF_NO),
    MAIN_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
    SUB_CATEGORY_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
    PRODUCT_ID INTEGER REFERENCES Stomaster.TBL_PRODUCT_MASTER(PRODUCT_ID),
    SALES_RATE_PER_QTY DECIMAL(15,6),
    QTY_PER_PACKING DECIMAL(15,2),
    DELIVERY_QTY DECIMAL(15,4),
    INVOICE_QTY DECIMAL(15,4),
    UOM VARCHAR(50),
    TOTAL_PACKING DECIMAL(15,4),
    ALTERNATE_UOM VARCHAR(500),
    TOTAL_PRODUCT_AMOUNT DECIMAL(15,4),
    VAT_PERCENTAGE DECIMAL(15,2),
    VAT_AMOUNT DECIMAL(15,4),
    FINAL_SALES_AMOUNT DECIMAL(15,4),
    TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,4),
    FINAL_SALES_AMOUNT_LC DECIMAL(15,4),
    REMARKS VARCHAR(2000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- TBL_CUSTOMER_RECEIPT_HDR
CREATE TABLE StoEntries.TBL_CUSTOMER_RECEIPT_HDR (
    SNO BIGSERIAL,
    RECEIPT_REF_NO VARCHAR(50) PRIMARY KEY,
    RECEIPT_DATE TIMESTAMP,
    PAYMENT_TYPE VARCHAR(50),
    COMPANY_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_MASTER(Company_Id),
    CUSTOMER_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_MASTER(Customer_Id),
    PAYMENT_MODE_ID INTEGER REFERENCES Stomaster.TBL_CUSTOMER_PAYMENT_MODE_MASTER(PAYMENT_MODE_ID),
    CR_BANK_CASH_ID INTEGER REFERENCES Stomaster.TBL_BANK_MASTER(BANK_ID),
    CR_ACCOUNT_ID INTEGER REFERENCES Stomaster.TBL_COMPANY_BANK_ACCOUNT_MASTER(Account_Id),
    DR_BANK_CASH_ID INTEGER REFERENCES Stomaster.TBL_BANK_MASTER(BANK_ID),
    TRANSACTION_REF_NO VARCHAR(100),
    TRANSACTION_DATE TIMESTAMP,
    CURRENCY_ID INTEGER REFERENCES Stomaster.TBL_CURRENCY_MASTER(CURRENCY_ID),
    RECEIPT_AMOUNT DECIMAL(15,2),
    EXCHANGE_RATE DECIMAL(15,2),
    RECEIPT_AMOUNT_LC DECIMAL(15,2),
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50),
    Submitted_By VARCHAR(50),
    Submitted_Date TIMESTAMP,
    Submitted_IP_Address VARCHAR(50),
    Tally_Ref_No VARCHAR(50),
    Tally_Sync_Status VARCHAR(20),
    Tally_Sync_Date TIMESTAMP,
    Tally_Sync_Person_Name VARCHAR(50)
);

-- TBL_CUSTOMER_RECEIPT_INVOICE_DTL
CREATE TABLE StoEntries.TBL_CUSTOMER_RECEIPT_INVOICE_DTL (
    SNO BIGSERIAL PRIMARY KEY,
    RECEIPT_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_CUSTOMER_RECEIPT_HDR(RECEIPT_REF_NO),
    TAX_INVOICE_REF_NO VARCHAR(50) REFERENCES StoEntries.TBL_TAX_INVOICE_HDR(TAX_INVOICE_REF_NO),
    ACTUAL_INVOICE_AMOUNT DECIMAL(15,2),
    ALREADY_PAID_AMOUNT DECIMAL(15,2),
    OUTSTANDING_INVOICE_AMOUNT DECIMAL(15,2),
    RECEIPT_INVOICE_ADJUST_AMOUNT DECIMAL(15,2),
    REMARKS VARCHAR(1000),
    STATUS_ENTRY VARCHAR(20),
    CREATED_BY VARCHAR(50),
    CREATED_DATE TIMESTAMP,
    CREATED_MAC_ADDRESS VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP,
    MODIFIED_MAC_ADDRESS VARCHAR(50)
);

-- =============================================
-- CREATE INDEXES FOR BETTER PERFORMANCE
-- =============================================

-- Stomaster indexes
CREATE INDEX idx_user_info_login_name ON Stomaster.TBL_USER_INFO_HDR(LOGIN_NAME);
CREATE INDEX idx_company_name ON Stomaster.TBL_COMPANY_MASTER(Company_Name);
CREATE INDEX idx_customer_name ON Stomaster.TBL_CUSTOMER_MASTER(Customer_Name);
CREATE INDEX idx_product_name ON Stomaster.TBL_PRODUCT_MASTER(PRODUCT_NAME);
CREATE INDEX idx_product_category ON Stomaster.TBL_PRODUCT_MASTER(MAIN_CATEGORY_ID, SUB_CATEGORY_ID);
CREATE INDEX idx_user_store_mapping_user ON Stomaster.TBL_USER_TO_STORE_MAPPING(USER_ID_USER_TO_ROLE);
CREATE INDEX idx_user_store_mapping_store ON Stomaster.TBL_USER_TO_STORE_MAPPING(STORE_ID_USER_TO_ROLE);
CREATE INDEX idx_user_store_mapping_company ON Stomaster.TBL_USER_TO_STORE_MAPPING(COMPANY_ID);

-- StoEntries indexes
CREATE INDEX idx_po_company ON StoEntries.TBL_PURCHASE_ORDER_HDR(COMPANY_ID);
CREATE INDEX idx_po_supplier ON StoEntries.TBL_PURCHASE_ORDER_HDR(SUPPLIER_ID);
CREATE INDEX idx_po_date ON StoEntries.TBL_PURCHASE_ORDER_HDR(PO_DATE);
CREATE INDEX idx_po_status ON StoEntries.TBL_PURCHASE_ORDER_HDR(STATUS_ENTRY);

CREATE INDEX idx_grn_po_ref ON StoEntries.TBL_GOODS_INWARD_GRN_HDR(PO_REF_NO);
CREATE INDEX idx_grn_date ON StoEntries.TBL_GOODS_INWARD_GRN_HDR(GRN_DATE);

CREATE INDEX idx_so_customer ON StoEntries.TBL_SALES_ORDER_HDR(CUSTOMER_ID);
CREATE INDEX idx_so_date ON StoEntries.TBL_SALES_ORDER_HDR(SALES_ORDER_DATE);
CREATE INDEX idx_so_company ON StoEntries.TBL_SALES_ORDER_HDR(COMPANY_ID);

CREATE INDEX idx_dn_source_ref ON StoEntries.TBL_DELIVERY_NOTE_HDR(DELIVERY_SOURCE_REF_NO);
CREATE INDEX idx_dn_date ON StoEntries.TBL_DELIVERY_NOTE_HDR(DELIVERY_DATE);

CREATE INDEX idx_tax_invoice_dn ON StoEntries.TBL_TAX_INVOICE_HDR(DELIVERY_NOTE_REF_NO);
CREATE INDEX idx_tax_invoice_date ON StoEntries.TBL_TAX_INVOICE_HDR(INVOICE_DATE);

CREATE INDEX idx_receipt_customer ON StoEntries.TBL_CUSTOMER_RECEIPT_HDR(CUSTOMER_ID);
CREATE INDEX idx_receipt_date ON StoEntries.TBL_CUSTOMER_RECEIPT_HDR(RECEIPT_DATE);

-- =============================================
-- COMMENTS FOR TABLES AND COLUMNS
-- =============================================

COMMENT ON SCHEMA Stomaster IS 'Store Master tables schema';
COMMENT ON SCHEMA StoEntries IS 'Store entries/transactions schema';

COMMENT ON TABLE Stomaster.TBL_USER_INFO_HDR IS 'User information header table';
COMMENT ON TABLE Stomaster.TBL_COMPANY_MASTER IS 'Company master data';
COMMENT ON TABLE StoEntries.TBL_PURCHASE_ORDER_HDR IS 'Purchase Order Header - Main document for purchases';
COMMENT ON TABLE StoEntries.TBL_SALES_ORDER_HDR IS 'Sales Order Header - Main document for sales';