import axios from 'axios';

const BASE_URL = 'http://localhost:5000/api';

let token = '';

const login = async () => {
    try {
        const res = await axios.post(`${BASE_URL}/auth/login`, {
            LOGIN_NAME: "Admin",
            PASSWORD_USER_HDR: "superadmin@123"
        });
        token = res.data.accessToken;
        axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
        console.log("🔑 Authenticated successfully as Admin.\n");
    } catch (error: any) {
        console.error("❌ Authentication failed:", error.response?.data?.msg || error.message);
        process.exit(1);
    }
};

// Sample data generator to help with required fields
const getSampleData = (domain: string) => {
    const randomSuffix = Math.floor(Math.random() * 10000);
    const common = { statusMaster: 'Active', remarks: `Generated by Test Script ${randomSuffix}` };

    const samples: Record<string, any> = {
        "companies": { companyName: `Test Company ${randomSuffix}`, tinNumber: `TIN-${randomSuffix}`, currencyId: 1 },
        "stores": { storeName: `Test Store ${randomSuffix}`, locationId: 1 },
        "categories": { mainCategoryName: `Test Category ${randomSuffix}` },
        "sub-categories": { subCategoryName: `Test Subcategory ${randomSuffix}`, mainCategoryId: 1 },
        "products": { productName: `Test Product ${randomSuffix}`, mainCategoryId: 1, subCategoryId: 1 },
        "countries": { countryName: `Test Country ${randomSuffix}`, countryCode: `TC${randomSuffix % 100}` },
        "regions": { regionName: `Test Region ${randomSuffix}`, countryId: 1 },
        "currencies": { currencyName: `CURR-${randomSuffix}`, currencySymbol: "$" },
        "locations": { locationName: `Test Location ${randomSuffix}` },
        "billing-locations": { billingLocationName: `Test Billing ${randomSuffix}` },
        "banks": { bankName: `Test Bank ${randomSuffix}` },
        "vat": { companyId: 1, vatPercentage: 15 },
        "payment-modes": { paymentModeName: `Card ${randomSuffix}` },
        "ledger-groups": { ledgerGroupName: `Test Group ${randomSuffix}`, ledgerGroupType: "Asset" },
        "ledger-master": { ledgerName: `Test Ledger ${randomSuffix}`, ledgerGroupId: 1, companyId: 1 },
        "field-headers": { fieldCategoryFldHdr: `Category ${randomSuffix}`, projectNameFldHdr: `Project ${randomSuffix}`, statusFldHdr: "Active" },
        "sales-person": { salesPersonName: `Agent ${randomSuffix}`, statusMaster: "Active" },
        "users": { loginName: `TestUser_${randomSuffix}`, passwordUserHdr: `Password@123`, role: 'User', mobileNo: '9999999999', mailId: `test${randomSuffix}@example.com`, status: 'Active' }
    };

    return { ...(samples[domain] || { name: `Test ${domain} ${randomSuffix}` }), ...common };
};

async function runTests() {
    await login();
    const MASTER_URL = BASE_URL;
    const domains = [
        "users", "companies", "stores", "categories", "sub-categories", "products",
        "suppliers", "countries", "regions", "districts", "customers",
        "currencies", "locations", "billing-locations", "additional-cost-types",
        "payment-terms", "account-heads", "customer-payment-modes", "banks",
        "exchange-rate", "vat", "user-store-mappings", "payment-modes",
        "ledger-groups", "ledger-master", "product-opening-stocks",
        "field-headers", "field-details", "product-company-category-mappings",
        "store-product-min-stock", "company-bank-accounts", "password-logs",
        "customer-addresses", "customer-files", "customer-billing-mappings",
        "customer-vat-settings", "customer-pricing", "customer-credit-limits",
        "credit-limit-files", "sales-person"
    ];

    console.log(`🚀 Starting API Automation Test for ${domains.length} domains...\n`);

    for (const domain of domains) {
        console.log(`--------------------------------------------------`);
        console.log(`📦 Testing Domain: [${domain.toUpperCase()}]`);

        try {
            // 1. Create One
            console.log(`   [POST] Creating record...`);
            const createRes = await axios.post(`${MASTER_URL}/${domain}`, {
                ...getSampleData(domain),
                audit: { user: "Tester", macAddress: "00:00:00:00" }
            });
            const newId = createRes.data.id;
            console.log(`   ✅ Created! ID: ${newId}`);

            // 2. Get All
            console.log(`   [GET] Fetching all...`);
            const getRes = await axios.get(`${MASTER_URL}/${domain}`);
            console.log(`   ✅ Fetched ${getRes.data.length} records.`);

            // 3. Update One
            console.log(`   [PUT] Updating record...`);
            await axios.put(`${MASTER_URL}/${domain}/${newId}`, {
                remarks: "Updated by automation",
                audit: { user: "Tester", macAddress: "00:00:00:00" }
            });
            console.log(`   ✅ Updated successfully.`);

            // 4. Delete One (Optional, but let's test Bulk Delete instead to keep DB clean)
            // Actually, let's test both.
            console.log(`   [DELETE] Deleting record...`);
            await axios.delete(`${MASTER_URL}/${domain}/${newId}`);
            console.log(`   ✅ Deleted successfully.`);

            // 5. Bulk Delete
            // Create two temporary ones to test bulk
            console.log(`   [BULK] testing bulk delete...`);
            const b1 = await axios.post(`${MASTER_URL}/${domain}`, { ...getSampleData(domain), audit: { user: "Tester" } });
            const b2 = await axios.post(`${MASTER_URL}/${domain}`, { ...getSampleData(domain), audit: { user: "Tester" } });
            const bulkIds = [b1.data.id, b2.data.id];

            await axios.post(`${MASTER_URL}/${domain}/bulk-delete`, { ids: bulkIds });
            console.log(`   ✅ Bulk deleted ${bulkIds.length} items.`);

            console.log(`\n✨ Domain [${domain}] passed all tests!`);

        } catch (error: any) {
            console.error(`   ❌ Failed domain [${domain}]:`, error.response?.data?.msg || error.message);
            // We continue to next domain even if one fails
        }
    }

    console.log(`\n🏁 Automation Test Finished.`);
}

runTests();
