ALTER TABLE "stoentries"."TBL_DELIVERY_NOTE_DTL" DROP CONSTRAINT "TBL_DELIVERY_NOTE_DTL_PO_DTL_SNO_TBL_PURCHASE_ORDER_DTL_SNO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_NOTE_DTL" DROP CONSTRAINT "TBL_DELIVERY_NOTE_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_DTL" DROP CONSTRAINT "TBL_EXPENSE_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_DTL" DROP CONSTRAINT "TBL_EXPENSE_DTL_PO_DTL_SNO_TBL_PURCHASE_ORDER_DTL_SNO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_HDR" DROP CONSTRAINT "TBL_EXPENSE_HDR_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_INWARD_GRN_DTL" DROP CONSTRAINT "TBL_GOODS_INWARD_GRN_DTL_PO_DTL_SNO_TBL_PURCHASE_ORDER_DTL_SNO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_INWARD_GRN_HDR" DROP CONSTRAINT "TBL_GOODS_INWARD_GRN_HDR_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_HDR" DROP CONSTRAINT "TBL_PURCHASE_INVOICE_HDR_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS" DROP CONSTRAINT "TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_CONVERSATION_DTL" DROP CONSTRAINT "TBL_PURCHASE_ORDER_CONVERSATION_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_DTL" DROP CONSTRAINT "TBL_PURCHASE_ORDER_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_FILES_UPLOAD" DROP CONSTRAINT "TBL_PURCHASE_ORDER_FILES_UPLOAD_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_DTL" DROP CONSTRAINT "TBL_SALES_ORDER_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_DTL" DROP CONSTRAINT "TBL_SALES_ORDER_DTL_PO_DTL_SNO_TBL_PURCHASE_ORDER_DTL_SNO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_DTL" DROP CONSTRAINT "TBL_SALES_PROFORMA_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_DTL" DROP CONSTRAINT "TBL_SALES_PROFORMA_DTL_PO_DTL_SNO_TBL_PURCHASE_ORDER_DTL_SNO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_DTL" DROP CONSTRAINT "TBL_TAX_INVOICE_DTL_PO_DTL_SNO_TBL_PURCHASE_ORDER_DTL_SNO_fk";
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_DTL" DROP CONSTRAINT "TBL_TAX_INVOICE_DTL_PO_REF_NO_TBL_PURCHASE_ORDER_HDR_PO_REF_NO_fk";
