CREATE TABLE "stomaster"."TBL_COMPANY_BASE_CURRENCY" (
	"ID" serial PRIMARY KEY NOT NULL,
	"Company_ID" integer,
	"BASE_CURRENCY_ID" integer,
	"UNREALIZED_GAIN_ACCOUNT_CODE" varchar(50),
	"UNREALIZED_LOSS_ACCOUNT_CODE" varchar(50),
	"REALIZED_GAIN_ACCOUNT_CODE" varchar(50),
	"REALIZED_LOSS_ACCOUNT_CODE" varchar(50),
	"AUTO_REVALUATION_FREQUENCY" varchar(20) DEFAULT 'MONTHLY',
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"MODIFIED_BY" varchar(50),
	"MODIFIED_DATE" timestamp,
	CONSTRAINT "TBL_COMPANY_BASE_CURRENCY_Company_ID_unique" UNIQUE("Company_ID")
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG" (
	"LOG_ID" serial PRIMARY KEY NOT NULL,
	"Company_ID" integer,
	"EXCHANGE_RATE_SNO" integer,
	"TRANSACTION_ID" integer,
	"RATE_VALUE_AT_USAGE" numeric(30, 8),
	"APPLIED_DATE" date,
	"USAGE_TYPE" varchar(30),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS" (
	"TRANSACTION_ID" serial PRIMARY KEY NOT NULL,
	"Company_ID" integer,
	"DOCUMENT_TYPE" varchar(30),
	"DOCUMENT_NUMBER" varchar(50),
	"DOCUMENT_DATE" date,
	"TRANSACTION_CURRENCY_ID" integer,
	"TRANSACTION_AMOUNT" numeric(30, 5),
	"BASE_CURRENCY_ID" integer,
	"BASE_AMOUNT" numeric(30, 5),
	"EXCHANGE_RATE_USED" numeric(30, 8),
	"EXCHANGE_RATE_SNO" integer,
	"ORIGINAL_BASE_AMOUNT" numeric(30, 5),
	"SETTLED_AMOUNT" numeric(30, 5) DEFAULT '0',
	"STATUS" varchar(20) DEFAULT 'PENDING',
	"REMARKS" varchar(500),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"CREATED_MAC_ADDRESS" varchar(50),
	"MODIFIED_BY" varchar(50),
	"MODIFIED_DATE" timestamp,
	"MODIFIED_MAC_ADDRESS" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_REALIZED_GAIN_LOSS" (
	"GL_ID" serial PRIMARY KEY NOT NULL,
	"Company_ID" integer,
	"TRANSACTION_ID" integer,
	"SETTLEMENT_DATE" date,
	"SETTLEMENT_AMOUNT" numeric(30, 5),
	"SETTLEMENT_RATE" numeric(30, 8),
	"SETTLEMENT_BASE_AMOUNT" numeric(30, 5),
	"ORIGINAL_BASE_AMOUNT" numeric(30, 5),
	"REALIZED_GAIN_LOSS" numeric(30, 5),
	"GL_TYPE" varchar(10),
	"JOURNAL_VOUCHER_NO" varchar(50),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_UNREALIZED_GAIN_LOSS" (
	"GL_ID" serial PRIMARY KEY NOT NULL,
	"Company_ID" integer,
	"TRANSACTION_ID" integer,
	"ACCOUNT_TYPE" varchar(30),
	"REVALUATION_DATE" date,
	"OLD_BASE_AMOUNT" numeric(30, 5),
	"NEW_BASE_AMOUNT" numeric(30, 5),
	"UNREALIZED_GAIN_LOSS" numeric(30, 5),
	"GL_TYPE" varchar(10),
	"JOURNAL_VOUCHER_NO" varchar(50),
	"REVERSAL_JOURNAL_VOUCHER_NO" varchar(50),
	"IS_REVERSED" boolean DEFAULT false,
	"STATUS" varchar(20) DEFAULT 'ACTIVE',
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp
);
--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COMPANY_BASE_CURRENCY" ADD CONSTRAINT "TBL_COMPANY_BASE_CURRENCY_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COMPANY_BASE_CURRENCY" ADD CONSTRAINT "TBL_COMPANY_BASE_CURRENCY_BASE_CURRENCY_ID_TBL_CURRENCY_MASTER_CURRENCY_ID_fk" FOREIGN KEY ("BASE_CURRENCY_ID") REFERENCES "stomaster"."TBL_CURRENCY_MASTER"("CURRENCY_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG" ADD CONSTRAINT "TBL_EXCHANGE_RATE_USAGE_LOG_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG" ADD CONSTRAINT "TBL_EXCHANGE_RATE_USAGE_LOG_EXCHANGE_RATE_SNO_TBL_EXCHANGE_RATE_MASTER_SNO_fk" FOREIGN KEY ("EXCHANGE_RATE_SNO") REFERENCES "stomaster"."TBL_EXCHANGE_RATE_MASTER"("SNO") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG" ADD CONSTRAINT "TBL_EXCHANGE_RATE_USAGE_LOG_TRANSACTION_ID_TBL_MULTI_CURRENCY_TRANSACTIONS_TRANSACTION_ID_fk" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS"("TRANSACTION_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS" ADD CONSTRAINT "TBL_MULTI_CURRENCY_TRANSACTIONS_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS" ADD CONSTRAINT "TBL_MULTI_CURRENCY_TRANSACTIONS_TRANSACTION_CURRENCY_ID_TBL_CURRENCY_MASTER_CURRENCY_ID_fk" FOREIGN KEY ("TRANSACTION_CURRENCY_ID") REFERENCES "stomaster"."TBL_CURRENCY_MASTER"("CURRENCY_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS" ADD CONSTRAINT "TBL_MULTI_CURRENCY_TRANSACTIONS_BASE_CURRENCY_ID_TBL_CURRENCY_MASTER_CURRENCY_ID_fk" FOREIGN KEY ("BASE_CURRENCY_ID") REFERENCES "stomaster"."TBL_CURRENCY_MASTER"("CURRENCY_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_REALIZED_GAIN_LOSS" ADD CONSTRAINT "TBL_REALIZED_GAIN_LOSS_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_REALIZED_GAIN_LOSS" ADD CONSTRAINT "TBL_REALIZED_GAIN_LOSS_TRANSACTION_ID_TBL_MULTI_CURRENCY_TRANSACTIONS_TRANSACTION_ID_fk" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS"("TRANSACTION_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_UNREALIZED_GAIN_LOSS" ADD CONSTRAINT "TBL_UNREALIZED_GAIN_LOSS_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_UNREALIZED_GAIN_LOSS" ADD CONSTRAINT "TBL_UNREALIZED_GAIN_LOSS_TRANSACTION_ID_TBL_MULTI_CURRENCY_TRANSACTIONS_TRANSACTION_ID_fk" FOREIGN KEY ("TRANSACTION_ID") REFERENCES "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS"("TRANSACTION_ID") ON DELETE no action ON UPDATE no action;