ALTER TABLE "stomaster"."CUSTOMER_CREDIT_LIMIT_FILE_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stomaster"."CUSTOMER_CREDIT_LIMIT_FILE_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_MASTER_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_MASTER_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_CUSTOMER_RECEIPT_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_CUSTOMER_RECEIPT_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE serial;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_FILES_UPLOAD" ALTER COLUMN "SNO" DROP IDENTITY;