CREATE TABLE "stomaster"."TBL_BUDGET_ALERT_LOG" (
	"ALERT_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_BUDGET_ALERT_LOG_ALERT_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"COST_CENTER_ID" integer,
	"ALERT_TYPE" varchar(50),
	"THRESHOLD_PERCENT" integer,
	"CURRENT_USAGE_PERCENT" numeric(5, 2),
	"BUDGETED_AMOUNT" numeric(30, 5),
	"ACTUAL_EXPENSE" numeric(30, 5),
	"COMMITTED_AMOUNT" numeric(30, 5),
	"ALERT_DATE" timestamp,
	"IS_NOTIFIED" boolean DEFAULT false,
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_COST_CENTER_ALLOCATION" (
	"ALLOCATION_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_COST_CENTER_ALLOCATION_ALLOCATION_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"COST_CENTER_ID" integer,
	"SOURCE_TABLE" varchar(50),
	"SOURCE_REF_NO" varchar(50),
	"SOURCE_LINE_SNO" integer,
	"EXPENSE_DATE" timestamp,
	"EXPENSE_CATEGORY" varchar(100),
	"CURRENCY_ID" integer,
	"EXPENSE_AMOUNT" numeric(30, 5),
	"LC_AMOUNT" numeric(30, 5),
	"ALLOCATION_PERCENTAGE" numeric(5, 2),
	"ALLOCATED_AMOUNT" numeric(30, 5),
	"APPROVAL_STATUS" varchar(20) DEFAULT 'PENDING',
	"STATUS_ENTRY" varchar(20) DEFAULT 'Active',
	"REMARKS" varchar(500),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_COST_CENTER_BUDGET" (
	"BUDGET_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_COST_CENTER_BUDGET_BUDGET_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"COST_CENTER_ID" integer,
	"FINANCIAL_YEAR" varchar(20),
	"PERIOD_START_DATE" date,
	"PERIOD_END_DATE" date,
	"BUDGET_AMOUNT" numeric(30, 5),
	"ACTUAL_EXPENSE" numeric(30, 5) DEFAULT '0',
	"COMMITTED_AMOUNT" numeric(30, 5) DEFAULT '0',
	"AVAILABLE_BUDGET" numeric(30, 5),
	"VARIANCE_AMOUNT" numeric(30, 5),
	"VARIANCE_PERCENTAGE" numeric(5, 2),
	"STATUS" varchar(20) DEFAULT 'Active'
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_COST_CENTER_MASTER" (
	"COST_CENTER_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_COST_CENTER_MASTER_COST_CENTER_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"COST_CENTER_CODE" varchar(50),
	"COST_CENTER_NAME" varchar(150),
	"COST_CENTER_TYPE" varchar(50),
	"DESCRIPTION" varchar(500),
	"BUDGET_ALERT_THRESHOLD" integer DEFAULT 80,
	"STATUS" varchar(20) DEFAULT 'Active',
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"CREATED_MAC_ADDRESS" varchar(50),
	CONSTRAINT "TBL_COST_CENTER_MASTER_COST_CENTER_CODE_unique" UNIQUE("COST_CENTER_CODE")
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_PROFIT_CENTER_ALLOCATION" (
	"ALLOCATION_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PROFIT_CENTER_ALLOCATION_ALLOCATION_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"PROFIT_CENTER_ID" integer,
	"SOURCE_TABLE" varchar(50),
	"SOURCE_REF_NO" varchar(50),
	"SOURCE_LINE_SNO" integer,
	"REVENUE_DATE" timestamp,
	"REVENUE_CATEGORY" varchar(100),
	"CURRENCY_ID" integer,
	"REVENUE_AMOUNT" numeric(30, 5),
	"LC_AMOUNT" numeric(30, 5),
	"ALLOCATION_PERCENTAGE" numeric(5, 2),
	"ALLOCATED_AMOUNT" numeric(30, 5),
	"STATUS_ENTRY" varchar(20) DEFAULT 'Active',
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_PROFIT_CENTER_MASTER" (
	"PROFIT_CENTER_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PROFIT_CENTER_MASTER_PROFIT_CENTER_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"PROFIT_CENTER_CODE" varchar(50),
	"PROFIT_CENTER_NAME" varchar(150),
	"MANAGER_NAME" varchar(100),
	"STATUS" varchar(20) DEFAULT 'Active',
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"CREATED_MAC_ADDRESS" varchar(50),
	CONSTRAINT "TBL_PROFIT_CENTER_MASTER_PROFIT_CENTER_CODE_unique" UNIQUE("PROFIT_CENTER_CODE")
);
--> statement-breakpoint
CREATE TABLE "stomaster"."TBL_PROFIT_CENTER_TARGET" (
	"TARGET_ID" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PROFIT_CENTER_TARGET_TARGET_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"Company_ID" integer,
	"PROFIT_CENTER_ID" integer,
	"FINANCIAL_YEAR" varchar(20),
	"PERIOD_NAME" varchar(50),
	"PERIOD_START_DATE" date,
	"PERIOD_END_DATE" date,
	"TARGET_AMOUNT" numeric(30, 5),
	"ACTUAL_REVENUE" numeric(30, 5) DEFAULT '0',
	"ACHIEVEMENT_PERCENT" numeric(5, 2)
);
--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ACCOUNTS_HEAD_MASTER" ALTER COLUMN "ACCOUNT_HEAD_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ACCOUNTS_HEAD_MASTER" ALTER COLUMN "ACCOUNT_HEAD_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_ACCOUNTS_HEAD_MASTER_ACCOUNT_HEAD_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ACCOUNTS_LEDGER_GROUP_MASTER" ALTER COLUMN "LEDGER_GROUP_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ACCOUNTS_LEDGER_GROUP_MASTER" ALTER COLUMN "LEDGER_GROUP_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_ACCOUNTS_LEDGER_GROUP_MASTER_LEDGER_GROUP_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ACCOUNTS_LEDGER_MASTER" ALTER COLUMN "LEDGER_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ACCOUNTS_LEDGER_MASTER" ALTER COLUMN "LEDGER_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_ACCOUNTS_LEDGER_MASTER_LEDGER_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ADDITIONAL_COST_TYPE_MASTER" ALTER COLUMN "ADDITIONAL_COST_TYPE_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ADDITIONAL_COST_TYPE_MASTER" ALTER COLUMN "ADDITIONAL_COST_TYPE_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_ADDITIONAL_COST_TYPE_MASTER_ADDITIONAL_COST_TYPE_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_BANK_MASTER" ALTER COLUMN "BANK_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_BANK_MASTER" ALTER COLUMN "BANK_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_BANK_MASTER_BANK_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Billing_Location_Master" ALTER COLUMN "Billing_Location_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Billing_Location_Master" ALTER COLUMN "Billing_Location_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Billing_Location_Master_Billing_Location_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Change_Password_Log" ALTER COLUMN "Sno" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Change_Password_Log" ALTER COLUMN "Sno" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Change_Password_Log_Sno_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Company_Bank_Account_Master" ALTER COLUMN "Account_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Company_Bank_Account_Master" ALTER COLUMN "Account_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Company_Bank_Account_Master_Account_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COMPANY_BASE_CURRENCY" ALTER COLUMN "ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COMPANY_BASE_CURRENCY" ALTER COLUMN "ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_COMPANY_BASE_CURRENCY_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Company_Master" ALTER COLUMN "Company_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Company_Master" ALTER COLUMN "Company_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Company_Master_Company_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_country_master" ALTER COLUMN "Country_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_country_master" ALTER COLUMN "Country_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_country_master_Country_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CURRENCY_MASTER" ALTER COLUMN "CURRENCY_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CURRENCY_MASTER" ALTER COLUMN "CURRENCY_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_CURRENCY_MASTER_CURRENCY_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Address_Details" ALTER COLUMN "Sno" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Address_Details" ALTER COLUMN "Sno" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Customer_Address_Details_Sno_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_COMPANY_WISE_BILLING_LOCATION_MAPPING" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_COMPANY_WISE_BILLING_LOCATION_MAPPING" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_CUSTOMER_COMPANY_WISE_BILLING_LOCATION_MAPPING_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Credit_Limit_Details" ALTER COLUMN "Sno" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Credit_Limit_Details" ALTER COLUMN "Sno" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Customer_Credit_Limit_Details_Sno_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Master" ALTER COLUMN "Customer_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Master" ALTER COLUMN "Customer_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Customer_Master_Customer_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_PAYMENT_MODE_MASTER" ALTER COLUMN "PAYMENT_MODE_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_PAYMENT_MODE_MASTER" ALTER COLUMN "PAYMENT_MODE_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_CUSTOMER_PAYMENT_MODE_MASTER_PAYMENT_MODE_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_PRODUCT_VAT_PERCENTAGE_SETTINGS" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_CUSTOMER_PRODUCT_VAT_PERCENTAGE_SETTINGS" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_CUSTOMER_PRODUCT_VAT_PERCENTAGE_SETTINGS_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Wise_Product_Price_Settings" ALTER COLUMN "Sno" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Customer_Wise_Product_Price_Settings" ALTER COLUMN "Sno" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Customer_Wise_Product_Price_Settings_Sno_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Department_Master" ALTER COLUMN "Department_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Department_Master" ALTER COLUMN "Department_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Department_Master_Department_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_District_Master" ALTER COLUMN "District_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_District_Master" ALTER COLUMN "District_id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_District_Master_District_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Employee_Master" ALTER COLUMN "Employee_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Employee_Master" ALTER COLUMN "Employee_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Employee_Master_Employee_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_MASTER" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_MASTER" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_EXCHANGE_RATE_MASTER_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG" ALTER COLUMN "LOG_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG" ALTER COLUMN "LOG_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_EXCHANGE_RATE_USAGE_LOG_LOG_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_field_dtl" ALTER COLUMN "activity_id_fld_dtl" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_field_dtl" ALTER COLUMN "activity_id_fld_dtl" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_field_dtl_activity_id_fld_dtl_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_field_hdr" ALTER COLUMN "field_id_fld_hdr" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_field_hdr" ALTER COLUMN "field_id_fld_hdr" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_field_hdr_field_id_fld_hdr_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Location_Master" ALTER COLUMN "Location_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Location_Master" ALTER COLUMN "Location_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Location_Master_Location_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS" ALTER COLUMN "TRANSACTION_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS" ALTER COLUMN "TRANSACTION_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_MULTI_CURRENCY_TRANSACTIONS_TRANSACTION_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PAYMENT_MODE_MASTER" ALTER COLUMN "PAYMENT_MODE_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PAYMENT_MODE_MASTER" ALTER COLUMN "PAYMENT_MODE_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PAYMENT_MODE_MASTER_PAYMENT_MODE_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PAYMENT_TERM_MASTER" ALTER COLUMN "PAYMENT_TERM_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PAYMENT_TERM_MASTER" ALTER COLUMN "PAYMENT_TERM_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PAYMENT_TERM_MASTER_PAYMENT_TERM_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Product_Company_Main_Category_Mapping" ALTER COLUMN "Sno" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Product_Company_Main_Category_Mapping" ALTER COLUMN "Sno" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Product_Company_Main_Category_Mapping_Sno_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_MAIN_CATEGORY_MASTER" ALTER COLUMN "MAIN_CATEGORY_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_MAIN_CATEGORY_MASTER" ALTER COLUMN "MAIN_CATEGORY_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PRODUCT_MAIN_CATEGORY_MASTER_MAIN_CATEGORY_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_MASTER" ALTER COLUMN "PRODUCT_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_MASTER" ALTER COLUMN "PRODUCT_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PRODUCT_MASTER_PRODUCT_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_OPENING_STOCK" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_OPENING_STOCK" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PRODUCT_OPENING_STOCK_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_SUB_CATEGORY_MASTER" ALTER COLUMN "SUB_CATEGORY_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PRODUCT_SUB_CATEGORY_MASTER" ALTER COLUMN "SUB_CATEGORY_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_PRODUCT_SUB_CATEGORY_MASTER_SUB_CATEGORY_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_REALIZED_GAIN_LOSS" ALTER COLUMN "GL_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_REALIZED_GAIN_LOSS" ALTER COLUMN "GL_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_REALIZED_GAIN_LOSS_GL_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_REGION_MASTER" ALTER COLUMN "REGION_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_REGION_MASTER" ALTER COLUMN "REGION_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_REGION_MASTER_REGION_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ROLE_MASTER" ALTER COLUMN "ROLE_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_ROLE_MASTER" ALTER COLUMN "ROLE_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_ROLE_MASTER_ROLE_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_SALES_PERSON_MASTER" ALTER COLUMN "Sales_Person_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_SALES_PERSON_MASTER" ALTER COLUMN "Sales_Person_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_SALES_PERSON_MASTER_Sales_Person_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_SCHEDULER_SETTINGS" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_SCHEDULER_SETTINGS" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_SCHEDULER_SETTINGS_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Store_Master" ALTER COLUMN "Store_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Store_Master" ALTER COLUMN "Store_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Store_Master_Store_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Store_Product_Minimum_Stock" ALTER COLUMN "Sno" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Store_Product_Minimum_Stock" ALTER COLUMN "Sno" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Store_Product_Minimum_Stock_Sno_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Supplier_Master" ALTER COLUMN "Supplier_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Supplier_Master" ALTER COLUMN "Supplier_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Supplier_Master_Supplier_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Tax_Master" ALTER COLUMN "Tax_Id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."tbl_Tax_Master" ALTER COLUMN "Tax_Id" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."tbl_Tax_Master_Tax_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_UNREALIZED_GAIN_LOSS" ALTER COLUMN "GL_ID" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_UNREALIZED_GAIN_LOSS" ALTER COLUMN "GL_ID" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_UNREALIZED_GAIN_LOSS_GL_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_USER_INFO_HDR" ALTER COLUMN "LOGIN_ID_USER_HDR" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_USER_INFO_HDR" ALTER COLUMN "LOGIN_ID_USER_HDR" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_USER_INFO_HDR_LOGIN_ID_USER_HDR_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_USER_TO_STORE_MAPPING" ALTER COLUMN "USER_TO_LOCATION_ID_USER_TO_ROLE" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_USER_TO_STORE_MAPPING" ALTER COLUMN "USER_TO_LOCATION_ID_USER_TO_ROLE" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_USER_TO_STORE_MAPPING_USER_TO_LOCATION_ID_USER_TO_ROLE_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_VAT_PERCENTAGE_SETTING" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_VAT_PERCENTAGE_SETTING" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stomaster"."TBL_VAT_PERCENTAGE_SETTING_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_CUSTOMER_RECEIPT_HDR" ALTER COLUMN "SNO" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_CUSTOMER_RECEIPT_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_CUSTOMER_RECEIPT_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_CUSTOMER_RECEIPT_INVOICE_DTL" ALTER COLUMN "SNO" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_CUSTOMER_RECEIPT_INVOICE_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_CUSTOMER_RECEIPT_INVOICE_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_NOTE_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_NOTE_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_DELIVERY_NOTE_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_NOTE_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_DELIVERY_NOTE_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_DELIVERY_NOTE_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_EXPENSE_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_EXPENSE_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_INWARD_GRN_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_INWARD_GRN_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_GOODS_INWARD_GRN_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_INWARD_GRN_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_GOODS_INWARD_GRN_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_GOODS_INWARD_GRN_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_JOURNAL_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_JOURNAL_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_JOURNAL_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_JOURNAL_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_JOURNAL_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_JOURNAL_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_INVOICE_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_FILES_UPLOAD" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_INVOICE_FILES_UPLOAD_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_INVOICE_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_CONVERSATION_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_CONVERSATION_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_ORDER_CONVERSATION_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_ORDER_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_FILES_UPLOAD" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_FILES_UPLOAD" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_ORDER_FILES_UPLOAD_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_ORDER_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_SALES_ORDER_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_ORDER_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_SALES_ORDER_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_SALES_PROFORMA_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_SALES_PROFORMA_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_SALES_PROFORMA_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_TAX_INVOICE_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_TAX_INVOICE_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TRIAL_BALANCE_DTL" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TRIAL_BALANCE_DTL" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_TRIAL_BALANCE_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TRIAL_BALANCE_HDR" ALTER COLUMN "SNO" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TRIAL_BALANCE_HDR" ALTER COLUMN "SNO" ADD GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_TRIAL_BALANCE_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_HDR" ADD COLUMN "COST_CENTER_ID" integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_HDR" ADD COLUMN "COST_CENTER_ID" integer;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_HDR" ADD COLUMN "SUPPLIER_PROFORMA_NUMBER" varchar(100);--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_HDR" ADD COLUMN "PROFIT_CENTER_ID" integer;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_BUDGET_ALERT_LOG" ADD CONSTRAINT "TBL_BUDGET_ALERT_LOG_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_BUDGET_ALERT_LOG" ADD CONSTRAINT "TBL_BUDGET_ALERT_LOG_COST_CENTER_ID_TBL_COST_CENTER_MASTER_COST_CENTER_ID_fk" FOREIGN KEY ("COST_CENTER_ID") REFERENCES "stomaster"."TBL_COST_CENTER_MASTER"("COST_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COST_CENTER_ALLOCATION" ADD CONSTRAINT "TBL_COST_CENTER_ALLOCATION_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COST_CENTER_ALLOCATION" ADD CONSTRAINT "TBL_COST_CENTER_ALLOCATION_COST_CENTER_ID_TBL_COST_CENTER_MASTER_COST_CENTER_ID_fk" FOREIGN KEY ("COST_CENTER_ID") REFERENCES "stomaster"."TBL_COST_CENTER_MASTER"("COST_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COST_CENTER_ALLOCATION" ADD CONSTRAINT "TBL_COST_CENTER_ALLOCATION_CURRENCY_ID_TBL_CURRENCY_MASTER_CURRENCY_ID_fk" FOREIGN KEY ("CURRENCY_ID") REFERENCES "stomaster"."TBL_CURRENCY_MASTER"("CURRENCY_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COST_CENTER_BUDGET" ADD CONSTRAINT "TBL_COST_CENTER_BUDGET_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COST_CENTER_BUDGET" ADD CONSTRAINT "TBL_COST_CENTER_BUDGET_COST_CENTER_ID_TBL_COST_CENTER_MASTER_COST_CENTER_ID_fk" FOREIGN KEY ("COST_CENTER_ID") REFERENCES "stomaster"."TBL_COST_CENTER_MASTER"("COST_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_COST_CENTER_MASTER" ADD CONSTRAINT "TBL_COST_CENTER_MASTER_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PROFIT_CENTER_ALLOCATION" ADD CONSTRAINT "TBL_PROFIT_CENTER_ALLOCATION_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PROFIT_CENTER_ALLOCATION" ADD CONSTRAINT "TBL_PROFIT_CENTER_ALLOCATION_PROFIT_CENTER_ID_TBL_PROFIT_CENTER_MASTER_PROFIT_CENTER_ID_fk" FOREIGN KEY ("PROFIT_CENTER_ID") REFERENCES "stomaster"."TBL_PROFIT_CENTER_MASTER"("PROFIT_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PROFIT_CENTER_ALLOCATION" ADD CONSTRAINT "TBL_PROFIT_CENTER_ALLOCATION_CURRENCY_ID_TBL_CURRENCY_MASTER_CURRENCY_ID_fk" FOREIGN KEY ("CURRENCY_ID") REFERENCES "stomaster"."TBL_CURRENCY_MASTER"("CURRENCY_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PROFIT_CENTER_MASTER" ADD CONSTRAINT "TBL_PROFIT_CENTER_MASTER_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PROFIT_CENTER_TARGET" ADD CONSTRAINT "TBL_PROFIT_CENTER_TARGET_Company_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("Company_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stomaster"."TBL_PROFIT_CENTER_TARGET" ADD CONSTRAINT "TBL_PROFIT_CENTER_TARGET_PROFIT_CENTER_ID_TBL_PROFIT_CENTER_MASTER_PROFIT_CENTER_ID_fk" FOREIGN KEY ("PROFIT_CENTER_ID") REFERENCES "stomaster"."TBL_PROFIT_CENTER_MASTER"("PROFIT_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_EXPENSE_HDR" ADD CONSTRAINT "TBL_EXPENSE_HDR_COST_CENTER_ID_TBL_COST_CENTER_MASTER_COST_CENTER_ID_fk" FOREIGN KEY ("COST_CENTER_ID") REFERENCES "stomaster"."TBL_COST_CENTER_MASTER"("COST_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_INVOICE_HDR" ADD CONSTRAINT "TBL_PURCHASE_INVOICE_HDR_COST_CENTER_ID_TBL_COST_CENTER_MASTER_COST_CENTER_ID_fk" FOREIGN KEY ("COST_CENTER_ID") REFERENCES "stomaster"."TBL_COST_CENTER_MASTER"("COST_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_TAX_INVOICE_HDR" ADD CONSTRAINT "TBL_TAX_INVOICE_HDR_PROFIT_CENTER_ID_TBL_PROFIT_CENTER_MASTER_PROFIT_CENTER_ID_fk" FOREIGN KEY ("PROFIT_CENTER_ID") REFERENCES "stomaster"."TBL_PROFIT_CENTER_MASTER"("PROFIT_CENTER_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_ORDER_HDR" DROP COLUMN "SUPLIER_PROFORMA_NUMBER";