CREATE TABLE "stoentries"."TBL_PURCHASE_PAYMENT_FILES_UPLOAD" (
	"SNO" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_PAYMENT_FILES_UPLOAD_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"PAYMENT_REF_NO" varchar(50),
	"DOCUMENT_TYPE" varchar(50),
	"DESCRIPTION_DETAILS" varchar(100),
	"FILE_NAME" varchar(150),
	"CONTENT_TYPE" varchar(50),
	"CONTENT_DATA" "bytea",
	"REMARKS" varchar(1000),
	"STATUS_MASTER" varchar(20),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"CREATED_IP_ADDRESS" varchar(50),
	"MODIFIED_BY" varchar(50),
	"MODIFIED_DATE" timestamp,
	"MODIFIED_IP_ADDRESS" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" (
	"SNO" bigint GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_PAYMENT_HDR_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"PAYMENT_REF_NO" varchar(50) PRIMARY KEY NOT NULL,
	"PAYMENT_DATE" timestamp,
	"PAYMENT_TYPE" varchar(50),
	"COMPANY_ID" integer,
	"SUPPLIER_ID" integer,
	"PAYMENT_MODE_ID" integer,
	"CR_BANK_CASH_ID" integer,
	"DR_BANK_CASH_ID" integer,
	"DR_ACCOUNT_ID" integer,
	"TRANSACTION_REF_NO" varchar(100),
	"TRANSACTION_DATE" timestamp,
	"CURRENCY_ID" integer,
	"PAYMENT_AMOUNT" numeric(30, 2),
	"EXCHANGE_RATE" numeric(30, 2),
	"PAYMENT_AMOUNT_LC" numeric(30, 2),
	"REMARKS" varchar(1000),
	"STATUS_ENTRY" varchar(20),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"CREATED_MAC_ADDRESS" varchar(50),
	"MODIFIED_BY" varchar(50),
	"MODIFIED_DATE" timestamp,
	"MODIFIED_MAC_ADDRESS" varchar(50),
	"Submitted_By" varchar(50),
	"Submitted_Date" timestamp,
	"Submitted_IP_Address" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "stoentries"."TBL_PURCHASE_PAYMENT_INV_DTL" (
	"SNO" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stoentries"."TBL_PURCHASE_PAYMENT_INV_DTL_SNO_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"PAYMENT_REF_NO" varchar(50),
	"PURCHASE_INVOICE_REF_NO" varchar(50),
	"ACTUAL_INVOICE_AMOUNT" numeric(30, 2),
	"ALREADY_PAID_AMOUNT" numeric(30, 2),
	"OUTSTANDING_INVOICE_AMOUNT" numeric(30, 2),
	"PAYMENT_INVOICE_ADJUST_AMOUNT" numeric(30, 2),
	"REMARKS" varchar(1000),
	"STATUS_ENTRY" varchar(20),
	"CREATED_BY" varchar(50),
	"CREATED_DATE" timestamp,
	"CREATED_MAC_ADDRESS" varchar(50),
	"MODIFIED_BY" varchar(50),
	"MODIFIED_DATE" timestamp,
	"MODIFIED_MAC_ADDRESS" varchar(50)
);
--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_FILES_UPLOAD" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_FILES_UPLOAD_PAYMENT_REF_NO_TBL_PURCHASE_PAYMENT_HDR_PAYMENT_REF_NO_fk" FOREIGN KEY ("PAYMENT_REF_NO") REFERENCES "stoentries"."TBL_PURCHASE_PAYMENT_HDR"("PAYMENT_REF_NO") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_COMPANY_ID_tbl_Company_Master_Company_Id_fk" FOREIGN KEY ("COMPANY_ID") REFERENCES "stomaster"."tbl_Company_Master"("Company_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_SUPPLIER_ID_tbl_Supplier_Master_Supplier_Id_fk" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "stomaster"."tbl_Supplier_Master"("Supplier_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_PAYMENT_MODE_ID_TBL_PAYMENT_MODE_MASTER_PAYMENT_MODE_ID_fk" FOREIGN KEY ("PAYMENT_MODE_ID") REFERENCES "stomaster"."TBL_PAYMENT_MODE_MASTER"("PAYMENT_MODE_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_CR_BANK_CASH_ID_TBL_BANK_MASTER_BANK_ID_fk" FOREIGN KEY ("CR_BANK_CASH_ID") REFERENCES "stomaster"."TBL_BANK_MASTER"("BANK_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_DR_BANK_CASH_ID_TBL_BANK_MASTER_BANK_ID_fk" FOREIGN KEY ("DR_BANK_CASH_ID") REFERENCES "stomaster"."TBL_BANK_MASTER"("BANK_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_DR_ACCOUNT_ID_tbl_Company_Bank_Account_Master_Account_Id_fk" FOREIGN KEY ("DR_ACCOUNT_ID") REFERENCES "stomaster"."tbl_Company_Bank_Account_Master"("Account_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_HDR" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_HDR_CURRENCY_ID_TBL_CURRENCY_MASTER_CURRENCY_ID_fk" FOREIGN KEY ("CURRENCY_ID") REFERENCES "stomaster"."TBL_CURRENCY_MASTER"("CURRENCY_ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_INV_DTL" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_INV_DTL_PAYMENT_REF_NO_TBL_PURCHASE_PAYMENT_HDR_PAYMENT_REF_NO_fk" FOREIGN KEY ("PAYMENT_REF_NO") REFERENCES "stoentries"."TBL_PURCHASE_PAYMENT_HDR"("PAYMENT_REF_NO") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stoentries"."TBL_PURCHASE_PAYMENT_INV_DTL" ADD CONSTRAINT "TBL_PURCHASE_PAYMENT_INV_DTL_PURCHASE_INVOICE_REF_NO_TBL_PURCHASE_INVOICE_HDR_PURCHASE_INVOICE_REF_NO_fk" FOREIGN KEY ("PURCHASE_INVOICE_REF_NO") REFERENCES "stoentries"."TBL_PURCHASE_INVOICE_HDR"("PURCHASE_INVOICE_REF_NO") ON DELETE no action ON UPDATE no action;