import { TBL_COMPANY_MASTER } from "./Stomaster.js";
import { TBL_SUPPLIER_MASTER } from "./Stomaster.js";
import { TBL_STORE_MASTER } from "./Stomaster.js";
import { TBL_PAYMENT_TERM_MASTER } from "./Stomaster.js";
import { TBL_CURRENCY_MASTER } from "./Stomaster.js";
import { TBL_PRODUCT_MAIN_CATEGORY_MASTER } from "./Stomaster.js";
import { TBL_PRODUCT_SUB_CATEGORY_MASTER } from "./Stomaster.js";
import { TBL_PRODUCT_MASTER } from "./Stomaster.js";
import { TBL_ADDITIONAL_COST_TYPE_MASTER } from "./Stomaster.js";
import { TBL_ACCOUNTS_HEAD_MASTER } from "./Stomaster.js";
import { TBL_CUSTOMER_MASTER } from "./Stomaster.js";
import { TBL_BILLING_LOCATION_MASTER } from "./Stomaster.js";
import { TBL_SALES_PERSON_MASTER } from "./Stomaster.js";
import { TBL_CUSTOMER_PAYMENT_MODE_MASTER } from "./Stomaster.js";
import { TBL_BANK_MASTER } from "./Stomaster.js";
import { TBL_COMPANY_BANK_ACCOUNT_MASTER } from "./Stomaster.js";

import { relations } from "drizzle-orm";
import { pgSchema, integer, varchar, text, timestamp, decimal, serial, bigserial, bigint, customType } from "drizzle-orm/pg-core";

export const stoentriesSchema = pgSchema("stoentries");

export const TBL_PURCHASE_ORDER_HDR = stoentriesSchema.table("TBL_PURCHASE_ORDER_HDR", {
  SNO: serial("SNO"),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).primaryKey(),
  PO_DATE: timestamp("PO_DATE", { mode: "date" }),
  PURCHASE_TYPE: varchar("PURCHASE_TYPE", { length: 20 }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  SUPPLIER_ID: integer("SUPPLIER_ID").references(() => TBL_SUPPLIER_MASTER.Supplier_Id),
  PO_STORE_ID: integer("PO_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  PAYMENT_TERM_ID: integer("PAYMENT_TERM_ID").references(() => TBL_PAYMENT_TERM_MASTER.PAYMENT_TERM_ID),
  MODE_OF_PAYMENT: varchar("MODE_OF_PAYMENT", { length: 25 }),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  SUPLIER_PROFORMA_NUMBER: varchar("SUPLIER_PROFORMA_NUMBER", { length: 100 }),
  SHIPMENT_MODE: varchar("SHIPMENT_MODE", { length: 100 }),
  PRICE_TERMS: varchar("PRICE_TERMS", { length: 150 }),
  ESTIMATED_SHIPMENT_DATE: timestamp("ESTIMATED_SHIPMENT_DATE", { mode: "date" }),
  SHIPMENT_REMARKS: varchar("SHIPMENT_REMARKS", { length: 2500 }),
  PRODUCT_HDR_AMOUNT: decimal("PRODUCT_HDR_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_ADDITIONAL_COST_AMOUNT: decimal("TOTAL_ADDITIONAL_COST_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_HDR_AMOUNT: decimal("TOTAL_PRODUCT_HDR_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_VAT_HDR_AMOUNT: decimal("TOTAL_VAT_HDR_AMOUNT", { precision: 15, scale: 2 }),
  FINAL_PURCHASE_HDR_AMOUNT: decimal("FINAL_PURCHASE_HDR_AMOUNT", { precision: 15, scale: 2 }),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 10, scale: 2 }),
  PRODUCT_HDR_AMOUNT_LC: decimal("PRODUCT_HDR_AMOUNT_LC", { precision: 15, scale: 4 }),
  TOTAL_ADDITIONAL_COST_AMOUNT_LC: decimal("TOTAL_ADDITIONAL_COST_AMOUNT_LC", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_HDR_AMOUNT_LC: decimal("TOTAL_PRODUCT_HDR_AMOUNT_LC", { precision: 15, scale: 4 }),
  TOTAL_VAT_HDR_AMOUNT_LC: decimal("TOTAL_VAT_HDR_AMOUNT_LC", { precision: 15, scale: 2 }),
  FINAL_PURCHASE_HDR_AMOUNT_LC: decimal("FINAL_PURCHASE_HDR_AMOUNT_LC", { precision: 15, scale: 2 }),
  SUBMITTED_BY: varchar("SUBMITTED_BY", { length: 50 }),
  SUBMITTED_DATE: timestamp("SUBMITTED_DATE", { mode: "date" }),
  SUBMITTED_IP_ADDRESS: varchar("SUBMITTED_IP_ADDRESS", { length: 50 }),
  PURCHASE_HEAD_RESPONSE_PERSON: varchar("PURCHASE_HEAD_RESPONSE_PERSON", { length: 50 }),
  PURCHASE_HEAD_RESPONSE_DATE: timestamp("PURCHASE_HEAD_RESPONSE_DATE", { mode: "date" }),
  PURCHASE_HEAD_RESPONSE_STATUS: varchar("PURCHASE_HEAD_RESPONSE_STATUS", { length: 50 }),
  PURCHASE_HEAD_RESPONSE_REMARKS: varchar("PURCHASE_HEAD_RESPONSE_REMARKS", { length: 500 }),
  PURCHASE_HEAD_RESPONSE_IP_ADDRESS: varchar("PURCHASE_HEAD_RESPONSE_IP_ADDRESS", { length: 50 }),
  RESPONSE_1_PERSON: varchar("RESPONSE_1_PERSON", { length: 50 }),
  RESPONSE_1_DATE: timestamp("RESPONSE_1_DATE", { mode: "date" }),
  RESPONSE_1_STATUS: varchar("RESPONSE_1_STATUS", { length: 50 }),
  RESPONSE_1_REMARKS: varchar("RESPONSE_1_REMARKS", { length: 5000 }),
  RESPONSE_1_IP_ADDRESS: varchar("RESPONSE_1_IP_ADDRESS", { length: 50 }),
  RESPONSE_2_PERSON: varchar("RESPONSE_2_PERSON", { length: 50 }),
  RESPONSE_2_DATE: timestamp("RESPONSE_2_DATE", { mode: "date" }),
  RESPONSE_2_STATUS: varchar("RESPONSE_2_STATUS", { length: 50 }),
  RESPONSE_2_REMARKS: varchar("RESPONSE_2_REMARKS", { length: 5000 }),
  RESPONSE_2_IP_ADDRESS: varchar("RESPONSE_2_IP_ADDRESS", { length: 50 }),
  FINAL_RESPONSE_PERSON: varchar("FINAL_RESPONSE_PERSON", { length: 50 }),
  FINAL_RESPONSE_DATE: timestamp("FINAL_RESPONSE_DATE", { mode: "date" }),
  FINAL_RESPONSE_STATUS: varchar("FINAL_RESPONSE_STATUS", { length: 50 }),
  FINAL_RESPONSE_REMARKS: varchar("FINAL_RESPONSE_REMARKS", { length: 5000 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_ORDER_DTL = stoentriesSchema.table("TBL_PURCHASE_ORDER_DTL", {
  SNO: serial("SNO").primaryKey(),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  REQUEST_STORE_ID: integer("REQUEST_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  MAIN_CATEGORY_ID: integer("MAIN_CATEGORY_ID").references(() => TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID),
  SUB_CATEGORY_ID: integer("SUB_CATEGORY_ID").references(() => TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  QTY_PER_PACKING: decimal("QTY_PER_PACKING", { precision: 15, scale: 2 }),
  TOTAL_QTY: decimal("TOTAL_QTY", { precision: 15, scale: 4 }),
  UOM: varchar("UOM", { length: 50 }),
  TOTAL_PACKING: decimal("TOTAL_PACKING", { precision: 15, scale: 4 }),
  ALTERNATE_UOM: varchar("ALTERNATE_UOM", { length: 500 }),
  RATE_PER_QTY: decimal("RATE_PER_QTY", { precision: 15, scale: 6 }),
  PRODUCT_AMOUNT: decimal("PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  DISCOUNT_PERCENTAGE: decimal("DISCOUNT_PERCENTAGE", { precision: 15, scale: 2 }),
  DISCOUNT_AMOUNT: decimal("DISCOUNT_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_PERCENTAGE: decimal("VAT_PERCENTAGE", { precision: 15, scale: 2 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_PRODUCT_AMOUNT: decimal("FINAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_PRODUCT_AMOUNT_LC: decimal("FINAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS = stoentriesSchema.table("TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS", {
  SNO: serial("SNO").primaryKey(),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  ADDITIONAL_COST_TYPE_ID: integer("ADDITIONAL_COST_TYPE_ID").references(() => TBL_ADDITIONAL_COST_TYPE_MASTER.ADDITIONAL_COST_TYPE_ID),
  ADDITIONAL_COST_AMOUNT: decimal("ADDITIONAL_COST_AMOUNT", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 1000 }),
  STATUS_MASTER: varchar("STATUS_MASTER", { length: 50 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_ORDER_FILES_UPLOAD = stoentriesSchema.table("TBL_PURCHASE_ORDER_FILES_UPLOAD", {
  SNO: serial("SNO").primaryKey(),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  DOCUMENT_TYPE: varchar("DOCUMENT_TYPE", { length: 50 }),
  DESCRIPTION_DETAILS: varchar("DESCRIPTION_DETAILS", { length: 100 }),
  FILE_NAME: varchar("FILE_NAME", { length: 150 }),
  CONTENT_TYPE: varchar("CONTENT_TYPE", { length: 50 }),
  CONTENT_DATA: customType({ dataType() { return "bytea"; } })("CONTENT_DATA"),
  REMARKS: varchar("REMARKS", { length: 1000 }),
  STATUS_MASTER: varchar("STATUS_MASTER", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_ORDER_CONVERSATION_DTL = stoentriesSchema.table("TBL_PURCHASE_ORDER_CONVERSATION_DTL", {
  SNO: serial("SNO").primaryKey(),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  RESPOND_PERSON: varchar("RESPOND_PERSON", { length: 50 }),
  DISCUSSION_DETAILS: text("DISCUSSION_DETAILS"),
  RESPONSE_STATUS: varchar("RESPONSE_STATUS", { length: 50 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 50 }),
  REMARKS: varchar("REMARKS", { length: 50 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_GOODS_INWARD_GRN_HDR = stoentriesSchema.table("TBL_GOODS_INWARD_GRN_HDR", {
  SNO: serial("SNO"),
  GRN_REF_NO: varchar("GRN_REF_NO", { length: 50 }).primaryKey(),
  GRN_DATE: timestamp("GRN_DATE", { mode: "date" }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  SOURCE_STORE_ID: integer("SOURCE_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  GRN_STORE_ID: integer("GRN_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  GRN_SOURCE: varchar("GRN_SOURCE", { length: 50 }),
  DELIVERY_NOTE_REF_NO: varchar("DELIVERY_NOTE_REF_NO", { length: 50 }),
  SUPPLIER_ID: integer("SUPPLIER_ID").references(() => TBL_SUPPLIER_MASTER.Supplier_Id),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  PURCHASE_INVOICE_REF_NO: varchar("PURCHASE_INVOICE_REF_NO", { length: 50 }),
  SUPPLIER_INVOICE_NUMBER: varchar("SUPPLIER_INVOICE_NUMBER", { length: 100 }),
  CONTAINER_NO: varchar("CONTAINER_NO", { length: 20 }),
  DRIVER_NAME: varchar("DRIVER_NAME", { length: 50 }),
  DRIVER_CONTACT_NUMBER: varchar("DRIVER_CONTACT_NUMBER", { length: 50 }),
  VEHICLE_NO: varchar("VEHICLE_NO", { length: 50 }),
  SEAL_NO: varchar("SEAL_NO", { length: 50 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_GOODS_INWARD_GRN_DTL = stoentriesSchema.table("TBL_GOODS_INWARD_GRN_DTL", {
  SNO: serial("SNO").primaryKey(),
  GRN_REF_NO: varchar("GRN_REF_NO", { length: 50 }).references(() => TBL_GOODS_INWARD_GRN_HDR.GRN_REF_NO),
  PO_DTL_SNO: integer("PO_DTL_SNO").references(() => TBL_PURCHASE_ORDER_DTL.SNO),
  MAIN_CATEGORY_ID: integer("MAIN_CATEGORY_ID").references(() => TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID),
  SUB_CATEGORY_ID: integer("SUB_CATEGORY_ID").references(() => TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  QTY_PER_PACKING: decimal("QTY_PER_PACKING", { precision: 15, scale: 2 }),
  TOTAL_QTY: decimal("TOTAL_QTY", { precision: 15, scale: 4 }),
  UOM: varchar("UOM", { length: 50 }),
  TOTAL_PACKING: decimal("TOTAL_PACKING", { precision: 15, scale: 4 }),
  ALTERNATE_UOM: varchar("ALTERNATE_UOM", { length: 500 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_INVOICE_HDR = stoentriesSchema.table("TBL_PURCHASE_INVOICE_HDR", {
  SNO: serial("SNO"),
  PURCHASE_INVOICE_REF_NO: varchar("PURCHASE_INVOICE_REF_NO", { length: 50 }).primaryKey(),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  INVOICE_NO: varchar("INVOICE_NO", { length: 100 }),
  INVOICE_DATE: timestamp("INVOICE_DATE", { mode: "date" }),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  PURCHASE_TYPE: varchar("PURCHASE_TYPE", { length: 20 }),
  SUPPLIER_ID: integer("SUPPLIER_ID").references(() => TBL_SUPPLIER_MASTER.Supplier_Id),
  STORE_ID: integer("STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  PAYMENT_TERM_ID: integer("PAYMENT_TERM_ID").references(() => TBL_PAYMENT_TERM_MASTER.PAYMENT_TERM_ID),
  MODE_OF_PAYMENT: varchar("MODE_OF_PAYMENT", { length: 25 }),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  PRICE_TERMS: varchar("PRICE_TERMS", { length: 150 }),
  PRODUCT_HDR_AMOUNT: decimal("PRODUCT_HDR_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_ADDITIONAL_COST_AMOUNT: decimal("TOTAL_ADDITIONAL_COST_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_HDR_AMOUNT: decimal("TOTAL_PRODUCT_HDR_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_VAT_HDR_AMOUNT: decimal("TOTAL_VAT_HDR_AMOUNT", { precision: 15, scale: 2 }),
  FINAL_INVOICE_HDR_AMOUNT: decimal("FINAL_INVOICE_HDR_AMOUNT", { precision: 15, scale: 2 }),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 10, scale: 2 }),
  PRODUCT_HDR_AMOUNT_LC: decimal("PRODUCT_HDR_AMOUNT_LC", { precision: 15, scale: 4 }),
  TOTAL_ADDITIONAL_COST_AMOUNT_LC: decimal("TOTAL_ADDITIONAL_COST_AMOUNT_LC", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_HDR_AMOUNT_LC: decimal("TOTAL_PRODUCT_HDR_AMOUNT_LC", { precision: 15, scale: 4 }),
  TOTAL_VAT_HDR_AMOUNT_LC: decimal("TOTAL_VAT_HDR_AMOUNT_LC", { precision: 15, scale: 2 }),
  FINAL_PURCHASE_INVOICE_AMOUNT_LC: decimal("FINAL_PURCHASE_INVOICE_AMOUNT_LC", { precision: 15, scale: 2 }),
  SUBMITTED_BY: varchar("SUBMITTED_BY", { length: 50 }),
  SUBMITTED_DATE: timestamp("SUBMITTED_DATE", { mode: "date" }),
  SUBMITTED_IP_ADDRESS: varchar("SUBMITTED_IP_ADDRESS", { length: 50 }),
  RESPONSE_1_PERSON: varchar("RESPONSE_1_PERSON", { length: 50 }),
  RESPONSE_1_DATE: timestamp("RESPONSE_1_DATE", { mode: "date" }),
  RESPONSE_1_STATUS: varchar("RESPONSE_1_STATUS", { length: 50 }),
  RESPONSE_1_REMARKS: varchar("RESPONSE_1_REMARKS", { length: 5000 }),
  RESPONSE_1_IP_ADDRESS: varchar("RESPONSE_1_IP_ADDRESS", { length: 50 }),
  RESPONSE_2_PERSON: varchar("RESPONSE_2_PERSON", { length: 50 }),
  RESPONSE_2_DATE: timestamp("RESPONSE_2_DATE", { mode: "date" }),
  RESPONSE_2_STATUS: varchar("RESPONSE_2_STATUS", { length: 50 }),
  RESPONSE_2_REMARKS: varchar("RESPONSE_2_REMARKS", { length: 5000 }),
  RESPONSE_2_IP_ADDRESS: varchar("RESPONSE_2_IP_ADDRESS", { length: 50 }),
  FINAL_RESPONSE_PERSON: varchar("FINAL_RESPONSE_PERSON", { length: 50 }),
  FINAL_RESPONSE_DATE: timestamp("FINAL_RESPONSE_DATE", { mode: "date" }),
  FINAL_RESPONSE_STATUS: varchar("FINAL_RESPONSE_STATUS", { length: 50 }),
  FINAL_RESPONSE_REMARKS: varchar("FINAL_RESPONSE_REMARKS", { length: 5000 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_INVOICE_DTL = stoentriesSchema.table("TBL_PURCHASE_INVOICE_DTL", {
  SNO: serial("SNO").primaryKey(),
  PURCHASE_INVOICE_REF_NO: varchar("PURCHASE_INVOICE_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  GRN_REF_NO: varchar("GRN_REF_NO", { length: 50 }).references(() => TBL_GOODS_INWARD_GRN_HDR.GRN_REF_NO),
  MAIN_CATEGORY_ID: integer("MAIN_CATEGORY_ID").references(() => TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID),
  SUB_CATEGORY_ID: integer("SUB_CATEGORY_ID").references(() => TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  QTY_PER_PACKING: decimal("QTY_PER_PACKING", { precision: 15, scale: 2 }),
  TOTAL_QTY: decimal("TOTAL_QTY", { precision: 15, scale: 4 }),
  UOM: varchar("UOM", { length: 50 }),
  TOTAL_PACKING: decimal("TOTAL_PACKING", { precision: 15, scale: 4 }),
  ALTERNATE_UOM: varchar("ALTERNATE_UOM", { length: 500 }),
  RATE_PER_QTY: decimal("RATE_PER_QTY", { precision: 15, scale: 6 }),
  PRODUCT_AMOUNT: decimal("PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  DISCOUNT_PERCENTAGE: decimal("DISCOUNT_PERCENTAGE", { precision: 15, scale: 2 }),
  DISCOUNT_AMOUNT: decimal("DISCOUNT_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_PERCENTAGE: decimal("VAT_PERCENTAGE", { precision: 15, scale: 2 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_PRODUCT_AMOUNT: decimal("FINAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_PRODUCT_AMOUNT_LC: decimal("FINAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS = stoentriesSchema.table("TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS", {
  SNO: serial("SNO").primaryKey(),
  PURCHASE_INVOICE_NO: varchar("PURCHASE_INVOICE_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  ADDITIONAL_COST_TYPE_ID: integer("ADDITIONAL_COST_TYPE_ID").references(() => TBL_ADDITIONAL_COST_TYPE_MASTER.ADDITIONAL_COST_TYPE_ID),
  ADDITIONAL_COST_AMOUNT: decimal("ADDITIONAL_COST_AMOUNT", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 1000 }),
  STATUS_MASTER: varchar("STATUS_MASTER", { length: 50 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_PURCHASE_INVOICE_FILES_UPLOAD = stoentriesSchema.table("TBL_PURCHASE_INVOICE_FILES_UPLOAD", {
  SNO: serial("SNO").primaryKey(),
  PURCHASE_INVOICE_REF_NO: varchar("PURCHASE_INVOICE_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  DOCUMENT_TYPE: varchar("DOCUMENT_TYPE", { length: 50 }),
  DESCRIPTION_DETAILS: varchar("DESCRIPTION_DETAILS", { length: 100 }),
  FILE_NAME: varchar("FILE_NAME", { length: 150 }),
  CONTENT_TYPE: varchar("CONTENT_TYPE", { length: 50 }),
  CONTENT_DATA: customType({ dataType() { return "bytea"; } })("CONTENT_DATA"),
  REMARKS: varchar("REMARKS", { length: 1000 }),
  STATUS_MASTER: varchar("STATUS_MASTER", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_EXPENSE_HDR = stoentriesSchema.table("TBL_EXPENSE_HDR", {
  SNO: serial("SNO"),
  EXPENSE_REF_NO: varchar("EXPENSE_REF_NO", { length: 50 }).primaryKey(),
  EXPENSE_DATE: timestamp("EXPENSE_DATE", { mode: "date" }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  EXPENSE_AGAINST: varchar("EXPENSE_AGAINST", { length: 50 }),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  ACCOUNT_HEAD_ID: integer("ACCOUNT_HEAD_ID").references(() => TBL_ACCOUNTS_HEAD_MASTER.ACCOUNT_HEAD_ID),
  EXPENSE_SUPPLIER_ID: integer("EXPENSE_SUPPLIER_ID").references(() => TBL_SUPPLIER_MASTER.Supplier_Id),
  EXPENSE_TYPE: varchar("EXPENSE_TYPE", { length: 100 }),
  TRA_EFD_RECEIPT_NO: varchar("TRA_EFD_RECEIPT_NO", { length: 100 }),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 15, scale: 2 }),
  TOTAL_EXPENSE_AMOUNT: decimal("TOTAL_EXPENSE_AMOUNT", { precision: 18, scale: 2 }),
  TOTAL_EXPENSE_AMOUNT_LC: decimal("TOTAL_EXPENSE_AMOUNT_LC", { precision: 18, scale: 2 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
  SUBMITTED_BY: varchar("SUBMITTED_BY", { length: 50 }),
  SUBMITTED_DATE: timestamp("SUBMITTED_DATE", { mode: "date" }),
  SUBMITTED_IP_ADDRESS: varchar("SUBMITTED_IP_ADDRESS", { length: 50 }),
});

export const TBL_EXPENSE_DTL = stoentriesSchema.table("TBL_EXPENSE_DTL", {
  SNO: serial("SNO").primaryKey(),
  EXPENSE_REF_NO: varchar("EXPENSE_REF_NO", { length: 50 }).references(() => TBL_EXPENSE_HDR.EXPENSE_REF_NO),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  PO_DTL_SNO: integer("PO_DTL_SNO").references(() => TBL_PURCHASE_ORDER_DTL.SNO),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  EXPENSE_AMOUNT: decimal("EXPENSE_AMOUNT", { precision: 18, scale: 2 }),
  EXPENSE_AMOUNT_LC: decimal("EXPENSE_AMOUNT_LC", { precision: 18, scale: 2 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_IP_ADDRESS: varchar("CREATED_IP_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_IP_ADDRESS: varchar("MODIFIED_IP_ADDRESS", { length: 50 }),
});

export const TBL_SALES_ORDER_HDR = stoentriesSchema.table("TBL_SALES_ORDER_HDR", {
  SNO: serial("SNO"),
  SALES_ORDER_REF_NO: varchar("SALES_ORDER_REF_NO", { length: 50 }).primaryKey(),
  SALES_ORDER_DATE: timestamp("SALES_ORDER_DATE", { mode: "date" }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  STORE_ID: integer("STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  CUSTOMER_ID: integer("CUSTOMER_ID").references(() => TBL_CUSTOMER_MASTER.Customer_Id),
  BILLING_LOCATION_ID: integer("BILLING_LOCATION_ID").references(() => TBL_BILLING_LOCATION_MASTER.Billing_Location_Id),
  SALES_PERSON_EMP_ID: integer("SALES_PERSON_EMP_ID").references(() => TBL_SALES_PERSON_MASTER.Sales_Person_ID),
  CREDIT_LIMIT_AMOUNT: decimal("CREDIT_LIMIT_AMOUNT", { precision: 15, scale: 2 }),
  CREDIT_LIMIT_DAYS: decimal("CREDIT_LIMIT_DAYS", { precision: 15, scale: 2 }),
  OUTSTANDING_AMOUNT: decimal("OUTSTANDING_AMOUNT", { precision: 15, scale: 2 }),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 15, scale: 2 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT: decimal("FINAL_SALES_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT_LC: decimal("FINAL_SALES_AMOUNT_LC", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  TEST_DESC: varchar("TEST_DESC", { length: 50 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
  SUBMITTED_BY: varchar("SUBMITTED_BY", { length: 50 }),
  SUBMITTED_DATE: timestamp("SUBMITTED_DATE", { mode: "date" }),
});

export const TBL_SALES_ORDER_DTL = stoentriesSchema.table("TBL_SALES_ORDER_DTL", {
  SNO: serial("SNO").primaryKey(),
  SALES_ORDER_REF_NO: varchar("SALES_ORDER_REF_NO", { length: 50 }).references(() => TBL_SALES_ORDER_HDR.SALES_ORDER_REF_NO),
  MAIN_CATEGORY_ID: integer("MAIN_CATEGORY_ID").references(() => TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID),
  SUB_CATEGORY_ID: integer("SUB_CATEGORY_ID").references(() => TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  STORE_STOCK_PCS: decimal("STORE_STOCK_PCS", { precision: 15, scale: 4 }),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  PO_DTL_SNO: integer("PO_DTL_SNO").references(() => TBL_PURCHASE_ORDER_DTL.SNO),
  PO_DTL_STOCK_QTY: decimal("PO_DTL_STOCK_QTY", { precision: 15, scale: 4 }),
  PURCHASE_RATE_PER_QTY: decimal("PURCHASE_RATE_PER_QTY", { precision: 15, scale: 6 }),
  PO_EXPENSE_AMOUNT: decimal("PO_EXPENSE_AMOUNT", { precision: 15, scale: 4 }),
  SALES_RATE_PER_QTY: decimal("SALES_RATE_PER_QTY", { precision: 15, scale: 6 }),
  QTY_PER_PACKING: decimal("QTY_PER_PACKING", { precision: 15, scale: 2 }),
  TOTAL_QTY: decimal("TOTAL_QTY", { precision: 15, scale: 4 }),
  UOM: varchar("UOM", { length: 50 }),
  TOTAL_PACKING: decimal("TOTAL_PACKING", { precision: 15, scale: 4 }),
  ALTERNATE_UOM: varchar("ALTERNATE_UOM", { length: 500 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_PERCENTAGE: decimal("VAT_PERCENTAGE", { precision: 15, scale: 2 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT: decimal("FINAL_SALES_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT_LC: decimal("FINAL_SALES_AMOUNT_LC", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
});

export const TBL_DELIVERY_NOTE_HDR = stoentriesSchema.table("TBL_DELIVERY_NOTE_HDR", {
  SNO: serial("SNO"),
  DELIVERY_NOTE_REF_NO: varchar("DELIVERY_NOTE_REF_NO", { length: 50 }).primaryKey(),
  DELIVERY_DATE: timestamp("DELIVERY_DATE", { mode: "date" }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  FROM_STORE_ID: integer("FROM_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  DELIVERY_SOURCE_TYPE: varchar("DELIVERY_SOURCE_TYPE", { length: 50 }),
  DELIVERY_SOURCE_REF_NO: varchar("DELIVERY_SOURCE_REF_NO", { length: 50 }),
  TO_STORE_ID: integer("TO_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  CUSTOMER_ID: integer("CUSTOMER_ID").references(() => TBL_CUSTOMER_MASTER.Customer_Id),
  TRUCK_NO: varchar("TRUCK_NO", { length: 50 }),
  TRAILER_NO: varchar("TRAILER_NO", { length: 50 }),
  DRIVER_NAME: varchar("DRIVER_NAME", { length: 50 }),
  DRIVER_CONTACT_NUMBER: varchar("DRIVER_CONTACT_NUMBER", { length: 50 }),
  SEAL_NO: varchar("SEAL_NO", { length: 50 }),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 15, scale: 2 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT: decimal("FINAL_SALES_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT_LC: decimal("FINAL_SALES_AMOUNT_LC", { precision: 15, scale: 4 }),
  TEST_DESC: varchar("TEST_DESC", { length: 50 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
  SUBMITTED_BY: varchar("SUBMITTED_BY", { length: 50 }),
  SUBMITTED_DATE: timestamp("SUBMITTED_DATE", { mode: "date" }),
  SUBMITTED_MAC_ADDRESS: varchar("SUBMITTED_MAC_ADDRESS", { length: 50 }),
});

export const TBL_DELIVERY_NOTE_DTL = stoentriesSchema.table("TBL_DELIVERY_NOTE_DTL", {
  SNO: serial("SNO").primaryKey(),
  DELIVERY_NOTE_REF_NO: varchar("DELIVERY_NOTE_REF_NO", { length: 50 }).references(() => TBL_DELIVERY_NOTE_HDR.DELIVERY_NOTE_REF_NO),
  SALES_ORDER_DTL_SNO: integer("SALES_ORDER_DTL_SNO"),
  PO_DTL_SNO: integer("PO_DTL_SNO").references(() => TBL_PURCHASE_ORDER_DTL.SNO),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  MAIN_CATEGORY_ID: integer("MAIN_CATEGORY_ID").references(() => TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID),
  SUB_CATEGORY_ID: integer("SUB_CATEGORY_ID").references(() => TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  SALES_RATE_PER_QTY: decimal("SALES_RATE_PER_QTY", { precision: 15, scale: 6 }),
  QTY_PER_PACKING: decimal("QTY_PER_PACKING", { precision: 15, scale: 2 }),
  REQUEST_QTY: decimal("REQUEST_QTY", { precision: 15, scale: 4 }),
  DELIVERY_QTY: decimal("DELIVERY_QTY", { precision: 15, scale: 4 }),
  UOM: varchar("UOM", { length: 50 }),
  TOTAL_PACKING: decimal("TOTAL_PACKING", { precision: 15, scale: 4 }),
  ALTERNATE_UOM: varchar("ALTERNATE_UOM", { length: 500 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_PERCENTAGE: decimal("VAT_PERCENTAGE", { precision: 15, scale: 2 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT: decimal("FINAL_SALES_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT_LC: decimal("FINAL_SALES_AMOUNT_LC", { precision: 15, scale: 4 }),
  STORE_STOCK_PCS: decimal("STORE_STOCK_PCS", { precision: 15, scale: 2 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
});

export const TBL_TAX_INVOICE_HDR = stoentriesSchema.table("TBL_TAX_INVOICE_HDR", {
  SNO: serial("SNO"),
  TAX_INVOICE_REF_NO: varchar("TAX_INVOICE_REF_NO", { length: 50 }).primaryKey(),
  INVOICE_DATE: timestamp("INVOICE_DATE", { mode: "date" }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  FROM_STORE_ID: integer("FROM_STORE_ID").references(() => TBL_STORE_MASTER.Store_Id),
  INVOICE_TYPE: varchar("INVOICE_TYPE", { length: 50 }),
  DELIVERY_NOTE_REF_NO: varchar("DELIVERY_NOTE_REF_NO", { length: 50 }).references(() => TBL_DELIVERY_NOTE_HDR.DELIVERY_NOTE_REF_NO),
  CUSTOMER_ID: integer("CUSTOMER_ID").references(() => TBL_CUSTOMER_MASTER.Customer_Id),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 15, scale: 2 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT: decimal("FINAL_SALES_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT_LC: decimal("FINAL_SALES_AMOUNT_LC", { precision: 15, scale: 4 }),
  TEST_DESC: varchar("TEST_DESC", { length: 50 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
  SUBMITTED_BY: varchar("SUBMITTED_BY", { length: 50 }),
  SUBMITTED_DATE: timestamp("SUBMITTED_DATE", { mode: "date" }),
  SUBMITTED_MAC_ADDRESS: varchar("SUBMITTED_MAC_ADDRESS", { length: 50 }),
});

export const TBL_TAX_INVOICE_DTL = stoentriesSchema.table("TBL_TAX_INVOICE_DTL", {
  SNO: serial("SNO").primaryKey(),
  TAX_INVOICE_REF_NO: varchar("TAX_INVOICE_REF_NO", { length: 50 }).references(() => TBL_TAX_INVOICE_HDR.TAX_INVOICE_REF_NO),
  DELIVERY_NOTE_DTL_SNO: integer("DELIVERY_NOTE_DTL_SNO"),
  PO_DTL_SNO: integer("PO_DTL_SNO").references(() => TBL_PURCHASE_ORDER_DTL.SNO),
  PO_REF_NO: varchar("PO_REF_NO", { length: 50 }).references(() => TBL_PURCHASE_ORDER_HDR.PO_REF_NO),
  MAIN_CATEGORY_ID: integer("MAIN_CATEGORY_ID").references(() => TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID),
  SUB_CATEGORY_ID: integer("SUB_CATEGORY_ID").references(() => TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID),
  PRODUCT_ID: integer("PRODUCT_ID").references(() => TBL_PRODUCT_MASTER.PRODUCT_ID),
  SALES_RATE_PER_QTY: decimal("SALES_RATE_PER_QTY", { precision: 15, scale: 6 }),
  QTY_PER_PACKING: decimal("QTY_PER_PACKING", { precision: 15, scale: 2 }),
  DELIVERY_QTY: decimal("DELIVERY_QTY", { precision: 15, scale: 4 }),
  INVOICE_QTY: decimal("INVOICE_QTY", { precision: 15, scale: 4 }),
  UOM: varchar("UOM", { length: 50 }),
  TOTAL_PACKING: decimal("TOTAL_PACKING", { precision: 15, scale: 4 }),
  ALTERNATE_UOM: varchar("ALTERNATE_UOM", { length: 500 }),
  TOTAL_PRODUCT_AMOUNT: decimal("TOTAL_PRODUCT_AMOUNT", { precision: 15, scale: 4 }),
  VAT_PERCENTAGE: decimal("VAT_PERCENTAGE", { precision: 15, scale: 2 }),
  VAT_AMOUNT: decimal("VAT_AMOUNT", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT: decimal("FINAL_SALES_AMOUNT", { precision: 15, scale: 4 }),
  TOTAL_PRODUCT_AMOUNT_LC: decimal("TOTAL_PRODUCT_AMOUNT_LC", { precision: 15, scale: 4 }),
  FINAL_SALES_AMOUNT_LC: decimal("FINAL_SALES_AMOUNT_LC", { precision: 15, scale: 4 }),
  REMARKS: varchar("REMARKS", { length: 2000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
});

export const TBL_CUSTOMER_RECEIPT_HDR = stoentriesSchema.table("TBL_CUSTOMER_RECEIPT_HDR", {
  SNO: bigserial("SNO", { mode: "number" }),
  RECEIPT_REF_NO: varchar("RECEIPT_REF_NO", { length: 50 }).primaryKey(),
  RECEIPT_DATE: timestamp("RECEIPT_DATE", { mode: "date" }),
  PAYMENT_TYPE: varchar("PAYMENT_TYPE", { length: 50 }),
  COMPANY_ID: integer("COMPANY_ID").references(() => TBL_COMPANY_MASTER.Company_Id),
  CUSTOMER_ID: integer("CUSTOMER_ID").references(() => TBL_CUSTOMER_MASTER.Customer_Id),
  PAYMENT_MODE_ID: integer("PAYMENT_MODE_ID").references(() => TBL_CUSTOMER_PAYMENT_MODE_MASTER.PAYMENT_MODE_ID),
  CR_BANK_CASH_ID: integer("CR_BANK_CASH_ID").references(() => TBL_BANK_MASTER.BANK_ID),
  CR_ACCOUNT_ID: integer("CR_ACCOUNT_ID").references(() => TBL_COMPANY_BANK_ACCOUNT_MASTER.Account_Id),
  DR_BANK_CASH_ID: integer("DR_BANK_CASH_ID").references(() => TBL_BANK_MASTER.BANK_ID),
  TRANSACTION_REF_NO: varchar("TRANSACTION_REF_NO", { length: 100 }),
  TRANSACTION_DATE: timestamp("TRANSACTION_DATE", { mode: "date" }),
  CURRENCY_ID: integer("CURRENCY_ID").references(() => TBL_CURRENCY_MASTER.CURRENCY_ID),
  RECEIPT_AMOUNT: decimal("RECEIPT_AMOUNT", { precision: 15, scale: 2 }),
  EXCHANGE_RATE: decimal("EXCHANGE_RATE", { precision: 15, scale: 2 }),
  RECEIPT_AMOUNT_LC: decimal("RECEIPT_AMOUNT_LC", { precision: 15, scale: 2 }),
  REMARKS: varchar("REMARKS", { length: 1000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
  Submitted_By: varchar("Submitted_By", { length: 50 }),
  Submitted_Date: timestamp("Submitted_Date", { mode: "date" }),
  Submitted_IP_Address: varchar("Submitted_IP_Address", { length: 50 }),
  Tally_Ref_No: varchar("Tally_Ref_No", { length: 50 }),
  Tally_Sync_Status: varchar("Tally_Sync_Status", { length: 20 }),
  Tally_Sync_Date: timestamp("Tally_Sync_Date", { mode: "date" }),
  Tally_Sync_Person_Name: varchar("Tally_Sync_Person_Name", { length: 50 }),
});

export const TBL_CUSTOMER_RECEIPT_INVOICE_DTL = stoentriesSchema.table("TBL_CUSTOMER_RECEIPT_INVOICE_DTL", {
  SNO: bigserial("SNO", { mode: "number" }).primaryKey(),
  RECEIPT_REF_NO: varchar("RECEIPT_REF_NO", { length: 50 }).references(() => TBL_CUSTOMER_RECEIPT_HDR.RECEIPT_REF_NO),
  TAX_INVOICE_REF_NO: varchar("TAX_INVOICE_REF_NO", { length: 50 }).references(() => TBL_TAX_INVOICE_HDR.TAX_INVOICE_REF_NO),
  ACTUAL_INVOICE_AMOUNT: decimal("ACTUAL_INVOICE_AMOUNT", { precision: 15, scale: 2 }),
  ALREADY_PAID_AMOUNT: decimal("ALREADY_PAID_AMOUNT", { precision: 15, scale: 2 }),
  OUTSTANDING_INVOICE_AMOUNT: decimal("OUTSTANDING_INVOICE_AMOUNT", { precision: 15, scale: 2 }),
  RECEIPT_INVOICE_ADJUST_AMOUNT: decimal("RECEIPT_INVOICE_ADJUST_AMOUNT", { precision: 15, scale: 2 }),
  REMARKS: varchar("REMARKS", { length: 1000 }),
  STATUS_ENTRY: varchar("STATUS_ENTRY", { length: 20 }),
  CREATED_BY: varchar("CREATED_BY", { length: 50 }),
  CREATED_DATE: timestamp("CREATED_DATE", { mode: "date" }),
  CREATED_MAC_ADDRESS: varchar("CREATED_MAC_ADDRESS", { length: 50 }),
  MODIFIED_BY: varchar("MODIFIED_BY", { length: 50 }),
  MODIFIED_DATE: timestamp("MODIFIED_DATE", { mode: "date" }),
  MODIFIED_MAC_ADDRESS: varchar("MODIFIED_MAC_ADDRESS", { length: 50 }),
});


export const TBL_PURCHASE_ORDER_HDRRelations = relations(TBL_PURCHASE_ORDER_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_PURCHASE_ORDER_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  supplier: one(TBL_SUPPLIER_MASTER, { fields: [TBL_PURCHASE_ORDER_HDR.SUPPLIER_ID], references: [TBL_SUPPLIER_MASTER.Supplier_Id] }),
  po_store: one(TBL_STORE_MASTER, { fields: [TBL_PURCHASE_ORDER_HDR.PO_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  payment_term: one(TBL_PAYMENT_TERM_MASTER, { fields: [TBL_PURCHASE_ORDER_HDR.PAYMENT_TERM_ID], references: [TBL_PAYMENT_TERM_MASTER.PAYMENT_TERM_ID] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_PURCHASE_ORDER_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_PURCHASE_ORDER_DTLRelations = relations(TBL_PURCHASE_ORDER_DTL, ({ one, many }) => ({
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_ORDER_DTL.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  request_store: one(TBL_STORE_MASTER, { fields: [TBL_PURCHASE_ORDER_DTL.REQUEST_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  main_category: one(TBL_PRODUCT_MAIN_CATEGORY_MASTER, { fields: [TBL_PURCHASE_ORDER_DTL.MAIN_CATEGORY_ID], references: [TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID] }),
  sub_category: one(TBL_PRODUCT_SUB_CATEGORY_MASTER, { fields: [TBL_PURCHASE_ORDER_DTL.SUB_CATEGORY_ID], references: [TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_PURCHASE_ORDER_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
}));

export const TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILSRelations = relations(TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS, ({ one, many }) => ({
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  additional_cost_type: one(TBL_ADDITIONAL_COST_TYPE_MASTER, { fields: [TBL_PURCHASE_ORDER_ADDITIONAL_COST_DETAILS.ADDITIONAL_COST_TYPE_ID], references: [TBL_ADDITIONAL_COST_TYPE_MASTER.ADDITIONAL_COST_TYPE_ID] }),
}));

export const TBL_PURCHASE_ORDER_FILES_UPLOADRelations = relations(TBL_PURCHASE_ORDER_FILES_UPLOAD, ({ one, many }) => ({
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_ORDER_FILES_UPLOAD.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
}));

export const TBL_PURCHASE_ORDER_CONVERSATION_DTLRelations = relations(TBL_PURCHASE_ORDER_CONVERSATION_DTL, ({ one, many }) => ({
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_ORDER_CONVERSATION_DTL.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
}));

export const TBL_GOODS_INWARD_GRN_HDRRelations = relations(TBL_GOODS_INWARD_GRN_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_GOODS_INWARD_GRN_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  source_store: one(TBL_STORE_MASTER, { fields: [TBL_GOODS_INWARD_GRN_HDR.SOURCE_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  grn_store: one(TBL_STORE_MASTER, { fields: [TBL_GOODS_INWARD_GRN_HDR.GRN_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  supplier: one(TBL_SUPPLIER_MASTER, { fields: [TBL_GOODS_INWARD_GRN_HDR.SUPPLIER_ID], references: [TBL_SUPPLIER_MASTER.Supplier_Id] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_GOODS_INWARD_GRN_HDR.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
}));

export const TBL_GOODS_INWARD_GRN_DTLRelations = relations(TBL_GOODS_INWARD_GRN_DTL, ({ one, many }) => ({
  grn_ref_no: one(TBL_GOODS_INWARD_GRN_HDR, { fields: [TBL_GOODS_INWARD_GRN_DTL.GRN_REF_NO], references: [TBL_GOODS_INWARD_GRN_HDR.GRN_REF_NO] }),
  po_dtl_sno: one(TBL_PURCHASE_ORDER_DTL, { fields: [TBL_GOODS_INWARD_GRN_DTL.PO_DTL_SNO], references: [TBL_PURCHASE_ORDER_DTL.SNO] }),
  main_category: one(TBL_PRODUCT_MAIN_CATEGORY_MASTER, { fields: [TBL_GOODS_INWARD_GRN_DTL.MAIN_CATEGORY_ID], references: [TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID] }),
  sub_category: one(TBL_PRODUCT_SUB_CATEGORY_MASTER, { fields: [TBL_GOODS_INWARD_GRN_DTL.SUB_CATEGORY_ID], references: [TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_GOODS_INWARD_GRN_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
}));

export const TBL_PURCHASE_INVOICE_HDRRelations = relations(TBL_PURCHASE_INVOICE_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_PURCHASE_INVOICE_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_INVOICE_HDR.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  supplier: one(TBL_SUPPLIER_MASTER, { fields: [TBL_PURCHASE_INVOICE_HDR.SUPPLIER_ID], references: [TBL_SUPPLIER_MASTER.Supplier_Id] }),
  store: one(TBL_STORE_MASTER, { fields: [TBL_PURCHASE_INVOICE_HDR.STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  payment_term: one(TBL_PAYMENT_TERM_MASTER, { fields: [TBL_PURCHASE_INVOICE_HDR.PAYMENT_TERM_ID], references: [TBL_PAYMENT_TERM_MASTER.PAYMENT_TERM_ID] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_PURCHASE_INVOICE_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_PURCHASE_INVOICE_DTLRelations = relations(TBL_PURCHASE_INVOICE_DTL, ({ one, many }) => ({
  purchase_invoice_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_INVOICE_DTL.PURCHASE_INVOICE_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  grn_ref_no: one(TBL_GOODS_INWARD_GRN_HDR, { fields: [TBL_PURCHASE_INVOICE_DTL.GRN_REF_NO], references: [TBL_GOODS_INWARD_GRN_HDR.GRN_REF_NO] }),
  main_category: one(TBL_PRODUCT_MAIN_CATEGORY_MASTER, { fields: [TBL_PURCHASE_INVOICE_DTL.MAIN_CATEGORY_ID], references: [TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID] }),
  sub_category: one(TBL_PRODUCT_SUB_CATEGORY_MASTER, { fields: [TBL_PURCHASE_INVOICE_DTL.SUB_CATEGORY_ID], references: [TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_PURCHASE_INVOICE_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
}));

export const TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILSRelations = relations(TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS, ({ one, many }) => ({
  purchase_invoice_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS.PURCHASE_INVOICE_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  additional_cost_type: one(TBL_ADDITIONAL_COST_TYPE_MASTER, { fields: [TBL_PURCHASE_INVOICE_ADDITIONAL_COST_DETAILS.ADDITIONAL_COST_TYPE_ID], references: [TBL_ADDITIONAL_COST_TYPE_MASTER.ADDITIONAL_COST_TYPE_ID] }),
}));

export const TBL_PURCHASE_INVOICE_FILES_UPLOADRelations = relations(TBL_PURCHASE_INVOICE_FILES_UPLOAD, ({ one, many }) => ({
  purchase_invoice_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_PURCHASE_INVOICE_FILES_UPLOAD.PURCHASE_INVOICE_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
}));

export const TBL_EXPENSE_HDRRelations = relations(TBL_EXPENSE_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_EXPENSE_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_EXPENSE_HDR.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  account_head: one(TBL_ACCOUNTS_HEAD_MASTER, { fields: [TBL_EXPENSE_HDR.ACCOUNT_HEAD_ID], references: [TBL_ACCOUNTS_HEAD_MASTER.ACCOUNT_HEAD_ID] }),
  expense_supplier: one(TBL_SUPPLIER_MASTER, { fields: [TBL_EXPENSE_HDR.EXPENSE_SUPPLIER_ID], references: [TBL_SUPPLIER_MASTER.Supplier_Id] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_EXPENSE_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_EXPENSE_DTLRelations = relations(TBL_EXPENSE_DTL, ({ one, many }) => ({
  expense_ref_no: one(TBL_EXPENSE_HDR, { fields: [TBL_EXPENSE_DTL.EXPENSE_REF_NO], references: [TBL_EXPENSE_HDR.EXPENSE_REF_NO] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_EXPENSE_DTL.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  po_dtl_sno: one(TBL_PURCHASE_ORDER_DTL, { fields: [TBL_EXPENSE_DTL.PO_DTL_SNO], references: [TBL_PURCHASE_ORDER_DTL.SNO] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_EXPENSE_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
}));

export const TBL_SALES_ORDER_HDRRelations = relations(TBL_SALES_ORDER_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_SALES_ORDER_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  store: one(TBL_STORE_MASTER, { fields: [TBL_SALES_ORDER_HDR.STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  customer: one(TBL_CUSTOMER_MASTER, { fields: [TBL_SALES_ORDER_HDR.CUSTOMER_ID], references: [TBL_CUSTOMER_MASTER.Customer_Id] }),
  billing_location: one(TBL_BILLING_LOCATION_MASTER, { fields: [TBL_SALES_ORDER_HDR.BILLING_LOCATION_ID], references: [TBL_BILLING_LOCATION_MASTER.Billing_Location_Id] }),
  sales_person_emp: one(TBL_SALES_PERSON_MASTER, { fields: [TBL_SALES_ORDER_HDR.SALES_PERSON_EMP_ID], references: [TBL_SALES_PERSON_MASTER.Sales_Person_ID] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_SALES_ORDER_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_SALES_ORDER_DTLRelations = relations(TBL_SALES_ORDER_DTL, ({ one, many }) => ({
  sales_order_ref_no: one(TBL_SALES_ORDER_HDR, { fields: [TBL_SALES_ORDER_DTL.SALES_ORDER_REF_NO], references: [TBL_SALES_ORDER_HDR.SALES_ORDER_REF_NO] }),
  main_category: one(TBL_PRODUCT_MAIN_CATEGORY_MASTER, { fields: [TBL_SALES_ORDER_DTL.MAIN_CATEGORY_ID], references: [TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID] }),
  sub_category: one(TBL_PRODUCT_SUB_CATEGORY_MASTER, { fields: [TBL_SALES_ORDER_DTL.SUB_CATEGORY_ID], references: [TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_SALES_ORDER_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_SALES_ORDER_DTL.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  po_dtl_sno: one(TBL_PURCHASE_ORDER_DTL, { fields: [TBL_SALES_ORDER_DTL.PO_DTL_SNO], references: [TBL_PURCHASE_ORDER_DTL.SNO] }),
}));

export const TBL_DELIVERY_NOTE_HDRRelations = relations(TBL_DELIVERY_NOTE_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_DELIVERY_NOTE_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  from_store: one(TBL_STORE_MASTER, { fields: [TBL_DELIVERY_NOTE_HDR.FROM_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  to_store: one(TBL_STORE_MASTER, { fields: [TBL_DELIVERY_NOTE_HDR.TO_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  customer: one(TBL_CUSTOMER_MASTER, { fields: [TBL_DELIVERY_NOTE_HDR.CUSTOMER_ID], references: [TBL_CUSTOMER_MASTER.Customer_Id] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_DELIVERY_NOTE_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_DELIVERY_NOTE_DTLRelations = relations(TBL_DELIVERY_NOTE_DTL, ({ one, many }) => ({
  delivery_note_ref_no: one(TBL_DELIVERY_NOTE_HDR, { fields: [TBL_DELIVERY_NOTE_DTL.DELIVERY_NOTE_REF_NO], references: [TBL_DELIVERY_NOTE_HDR.DELIVERY_NOTE_REF_NO] }),
  po_dtl_sno: one(TBL_PURCHASE_ORDER_DTL, { fields: [TBL_DELIVERY_NOTE_DTL.PO_DTL_SNO], references: [TBL_PURCHASE_ORDER_DTL.SNO] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_DELIVERY_NOTE_DTL.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  main_category: one(TBL_PRODUCT_MAIN_CATEGORY_MASTER, { fields: [TBL_DELIVERY_NOTE_DTL.MAIN_CATEGORY_ID], references: [TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID] }),
  sub_category: one(TBL_PRODUCT_SUB_CATEGORY_MASTER, { fields: [TBL_DELIVERY_NOTE_DTL.SUB_CATEGORY_ID], references: [TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_DELIVERY_NOTE_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
}));

export const TBL_TAX_INVOICE_HDRRelations = relations(TBL_TAX_INVOICE_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_TAX_INVOICE_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  from_store: one(TBL_STORE_MASTER, { fields: [TBL_TAX_INVOICE_HDR.FROM_STORE_ID], references: [TBL_STORE_MASTER.Store_Id] }),
  delivery_note_ref_no: one(TBL_DELIVERY_NOTE_HDR, { fields: [TBL_TAX_INVOICE_HDR.DELIVERY_NOTE_REF_NO], references: [TBL_DELIVERY_NOTE_HDR.DELIVERY_NOTE_REF_NO] }),
  customer: one(TBL_CUSTOMER_MASTER, { fields: [TBL_TAX_INVOICE_HDR.CUSTOMER_ID], references: [TBL_CUSTOMER_MASTER.Customer_Id] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_TAX_INVOICE_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_TAX_INVOICE_DTLRelations = relations(TBL_TAX_INVOICE_DTL, ({ one, many }) => ({
  tax_invoice_ref_no: one(TBL_TAX_INVOICE_HDR, { fields: [TBL_TAX_INVOICE_DTL.TAX_INVOICE_REF_NO], references: [TBL_TAX_INVOICE_HDR.TAX_INVOICE_REF_NO] }),
  po_dtl_sno: one(TBL_PURCHASE_ORDER_DTL, { fields: [TBL_TAX_INVOICE_DTL.PO_DTL_SNO], references: [TBL_PURCHASE_ORDER_DTL.SNO] }),
  po_ref_no: one(TBL_PURCHASE_ORDER_HDR, { fields: [TBL_TAX_INVOICE_DTL.PO_REF_NO], references: [TBL_PURCHASE_ORDER_HDR.PO_REF_NO] }),
  main_category: one(TBL_PRODUCT_MAIN_CATEGORY_MASTER, { fields: [TBL_TAX_INVOICE_DTL.MAIN_CATEGORY_ID], references: [TBL_PRODUCT_MAIN_CATEGORY_MASTER.MAIN_CATEGORY_ID] }),
  sub_category: one(TBL_PRODUCT_SUB_CATEGORY_MASTER, { fields: [TBL_TAX_INVOICE_DTL.SUB_CATEGORY_ID], references: [TBL_PRODUCT_SUB_CATEGORY_MASTER.SUB_CATEGORY_ID] }),
  product: one(TBL_PRODUCT_MASTER, { fields: [TBL_TAX_INVOICE_DTL.PRODUCT_ID], references: [TBL_PRODUCT_MASTER.PRODUCT_ID] }),
}));

export const TBL_CUSTOMER_RECEIPT_HDRRelations = relations(TBL_CUSTOMER_RECEIPT_HDR, ({ one, many }) => ({
  company: one(TBL_COMPANY_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.COMPANY_ID], references: [TBL_COMPANY_MASTER.Company_Id] }),
  customer: one(TBL_CUSTOMER_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.CUSTOMER_ID], references: [TBL_CUSTOMER_MASTER.Customer_Id] }),
  payment_mode: one(TBL_CUSTOMER_PAYMENT_MODE_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.PAYMENT_MODE_ID], references: [TBL_CUSTOMER_PAYMENT_MODE_MASTER.PAYMENT_MODE_ID] }),
  cr_bank_cash: one(TBL_BANK_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.CR_BANK_CASH_ID], references: [TBL_BANK_MASTER.BANK_ID] }),
  cr_account: one(TBL_COMPANY_BANK_ACCOUNT_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.CR_ACCOUNT_ID], references: [TBL_COMPANY_BANK_ACCOUNT_MASTER.Account_Id] }),
  dr_bank_cash: one(TBL_BANK_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.DR_BANK_CASH_ID], references: [TBL_BANK_MASTER.BANK_ID] }),
  currency: one(TBL_CURRENCY_MASTER, { fields: [TBL_CUSTOMER_RECEIPT_HDR.CURRENCY_ID], references: [TBL_CURRENCY_MASTER.CURRENCY_ID] }),
}));

export const TBL_CUSTOMER_RECEIPT_INVOICE_DTLRelations = relations(TBL_CUSTOMER_RECEIPT_INVOICE_DTL, ({ one, many }) => ({
  receipt_ref_no: one(TBL_CUSTOMER_RECEIPT_HDR, { fields: [TBL_CUSTOMER_RECEIPT_INVOICE_DTL.RECEIPT_REF_NO], references: [TBL_CUSTOMER_RECEIPT_HDR.RECEIPT_REF_NO] }),
  tax_invoice_ref_no: one(TBL_TAX_INVOICE_HDR, { fields: [TBL_CUSTOMER_RECEIPT_INVOICE_DTL.TAX_INVOICE_REF_NO], references: [TBL_TAX_INVOICE_HDR.TAX_INVOICE_REF_NO] }),
}));
